import json
import sys
import os

def generate_imagej_macro(result, output_path, image_path=None):
    particles = result.get("particles", [])
    scale_factor = result.get("scale_factor", 1.0)
    unit = "nm" if scale_factor != 1.0 else "pixel"
    
    macro_lines = []
    macro_lines.append("// ImageJ Macro - Particle Analysis Results")
    macro_lines.append("// Generated by Particle Analyzer")
    macro_lines.append("")
    
    if image_path and os.path.exists(image_path):
        macro_lines.append(f'open("{image_path}");')
        macro_lines.append("")
    
    macro_lines.append("// Set scale")
    macro_lines.append(f'run("Set Scale...", "distance=1 known={scale_factor} unit={unit} global");')
    macro_lines.append("")
    
    macro_lines.append("// Create ROI Manager")
    macro_lines.append('roiManager("reset");')
    macro_lines.append("")
    
    macro_lines.append("// Add particle ROIs")
    for i, particle in enumerate(particles):
        contour = particle.get("contour", [])
        if len(contour) > 0:
            x_coords = [str(p[0]) for p in contour]
            y_coords = [str(p[1]) for p in contour]
            
            macro_lines.append(f'// Particle {particle["id"]}')
            macro_lines.append(f'x = newArray({",".join(x_coords)});')
            macro_lines.append(f'y = newArray({",".join(y_coords)});')
            macro_lines.append('makeSelection("polygon", x, y);')
            macro_lines.append(f'roiManager("add");')
            macro_lines.append(f'roiManager("rename", "Particle_{particle["id"]}");')
            macro_lines.append("")
    
    macro_lines.append("// Set ROI display options")
    macro_lines.append('roiManager("Show All");')
    macro_lines.append('roiManager("Set Color", "green");')
    macro_lines.append("")
    
    macro_lines.append("// Generate results table")
    macro_lines.append('Table.reset("Results");')
    macro_lines.append('Table.setHeading("ID");')
    macro_lines.append('Table.setHeading("Area");')
    macro_lines.append('Table.setHeading("Perimeter");')
    macro_lines.append('Table.setHeading("Circularity");')
    macro_lines.append('Table.setHeading("Centroid_X");')
    macro_lines.append('Table.setHeading("Centroid_Y");')
    macro_lines.append("")
    
    for i, particle in enumerate(particles):
        macro_lines.append(f'Table.addRow();')
        macro_lines.append(f'Table.setResult("ID", {i}, {particle["id"]});')
        macro_lines.append(f'Table.setResult("Area", {i}, {particle["area"]:.2f});')
        macro_lines.append(f'Table.setResult("Perimeter", {i}, {particle["perimeter"]:.2f});')
        macro_lines.append(f'Table.setResult("Circularity", {i}, {particle["circularity"]:.4f});')
        macro_lines.append(f'Table.setResult("Centroid_X", {i}, {particle["centroid"]["x"]});')
        macro_lines.append(f'Table.setResult("Centroid_Y", {i}, {particle["centroid"]["y"]});')
    
    macro_lines.append("")
    macro_lines.append("// Show results")
    macro_lines.append('Table.show("Results");')
    macro_lines.append("")
    
    macro_lines.append("// Statistical Summary")
    macro_lines.append(f'print("Total Particles: {result.get(\'total_count\', 0)}");')
    macro_lines.append(f'print("Average Area: {result.get(\'statistics\', {}).get(\'avg_area\', 0):.2f} {unit}^2");')
    macro_lines.append(f'print("Average Circularity: {result.get(\'statistics\', {}).get(\'avg_circularity\', 0):.4f}");')
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(macro_lines))
    
    return True

def generate_imagej_script(result, output_path, image_path=None):
    particles = result.get("particles", [])
    scale_factor = result.get("scale_factor", 1.0)
    unit = "nm" if scale_factor != 1.0 else "pixel"
    
    script_lines = []
    script_lines.append("#@ ImagePlus imp")
    script_lines.append("")
    script_lines.append("// ImageJ Script (Groovy) - Particle Analysis Results")
    script_lines.append("// Generated by Particle Analyzer")
    script_lines.append("")
    
    script_lines.append("import ij.IJ;")
    script_lines.append("import ij.gui.Roi;")
    script_lines.append("import ij.gui.PolygonRoi;")
    script_lines.append("import ij.measure.ResultsTable;")
    script_lines.append("import ij.plugin.frame.RoiManager;")
    script_lines.append("")
    
    script_lines.append("// Set scale")
    script_lines.append(f'IJ.run(imp, "Set Scale...", "distance=1 known={scale_factor} unit={unit} global");')
    script_lines.append("")
    
    script_lines.append("// Get ROI Manager")
    script_lines.append("def rm = RoiManager.getInstance();")
    script_lines.append("if (rm == null) rm = new RoiManager();")
    script_lines.append("rm.reset();")
    script_lines.append("")
    
    script_lines.append("// Add particle ROIs")
    for particle in particles:
        contour = particle.get("contour", [])
        if len(contour) > 0:
            x_coords = [str(p[0]) for p in contour]
            y_coords = [str(p[1]) for p in contour]
            
            script_lines.append(f'// Particle {particle["id"]}')
            script_lines.append(f'def x{i} = [{",".join(x_coords)}] as int[];')
            script_lines.append(f'def y{i} = [{",".join(y_coords)}] as int[];')
            script_lines.append(f'def roi{i} = new PolygonRoi(x{i}, y{i}, x{i}.length, Roi.POLYGON);')
            script_lines.append(f'rm.addRoi(roi{i});')
            script_lines.append(f'rm.rename(rm.getCount()-1, "Particle_{particle[\'id\']}");')
            script_lines.append("")
    
    script_lines.append("// Show all ROIs")
    script_lines.append("rm.setVisible(true);")
    script_lines.append("rm.runCommand(imp, \"Show All\");")
    script_lines.append("")
    
    script_lines.append("// Create Results Table")
    script_lines.append("def rt = new ResultsTable();")
    script_lines.append("")
    
    for i, particle in enumerate(particles):
        script_lines.append("rt.incrementCounter();")
        script_lines.append(f'rt.addValue("ID", {particle["id"]});')
        script_lines.append(f'rt.addValue("Area", {particle["area"]});')
        script_lines.append(f'rt.addValue("Perimeter", {particle["perimeter"]});')
        script_lines.append(f'rt.addValue("Circularity", {particle["circularity"]});')
        script_lines.append(f'rt.addValue("Centroid_X", {particle["centroid"]["x"]});')
        script_lines.append(f'rt.addValue("Centroid_Y", {particle["centroid"]["y"]});')
    
    script_lines.append("")
    script_lines.append("rt.show(\"Results\");")
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(script_lines))
    
    return True

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(json.dumps({"error": "缺少参数"}))
        sys.exit(1)
    
    json_path = sys.argv[1]
    output_path = sys.argv[2]
    image_path = sys.argv[3] if len(sys.argv) > 3 else None
    script_type = sys.argv[4] if len(sys.argv) > 4 else 'macro'
    
    with open(json_path, 'r') as f:
        result = json.load(f)
    
    if script_type == 'script':
        success = generate_imagej_script(result, output_path, image_path)
    else:
        success = generate_imagej_macro(result, output_path, image_path)
    
    print(json.dumps({"success": success, "output_path": output_path}))
