import type { ConfigValue, KconfigSymbol, DiffResult, DiffItem, MinimalConfigResult } from '../../shared/types.js';

export const generateConfigContent = (
  values: ConfigValue,
  symbols: Record<string, KconfigSymbol>
): string => {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push(`# Generated by Kconfig Web Editor`);
  lines.push(`# Date: ${now}`);
  lines.push('');

  for (const [name, symbol] of Object.entries(symbols)) {
    const value = values[name] ?? symbol.defaultValue;

    if (value === false || value === undefined || value === 'n') {
      lines.push(`# CONFIG_${name} is not set`);
    } else if (value === true || value === 'y') {
      lines.push(`CONFIG_${name}=y`);
    } else if (value === 'm') {
      lines.push(`CONFIG_${name}=m`);
    } else if (symbol.type === 'string') {
      lines.push(`CONFIG_${name}="${value}"`);
    } else if (symbol.type === 'int' || symbol.type === 'hex') {
      lines.push(`CONFIG_${name}=${value}`);
    }
  }

  lines.push('');
  return lines.join('\n');
};

export const checkDependencies = (
  symbolName: string,
  values: ConfigValue,
  symbols: Record<string, KconfigSymbol>
): { valid: boolean; unmetDeps: string[] } => {
  const symbol = symbols[symbolName];
  if (!symbol) return { valid: true, unmetDeps: [] };

  const unmetDeps: string[] = [];

  for (const dep of symbol.dependencies) {
    const depValue = values[dep];
    if (depValue !== true && depValue !== 'y' && depValue !== 'm') {
      unmetDeps.push(dep);
    }
  }

  return {
    valid: unmetDeps.length === 0,
    unmetDeps,
  };
};

const isFalsy = (v: string | boolean | number | undefined): boolean => {
  return !v || v === 'n';
};

const isTruthy = (v: string | boolean | number | undefined): boolean => {
  return v === true || v === 'y' || v === 'm';
};

export const resolveDependencies = (
  symbolName: string,
  newValue: string | boolean,
  currentValues: ConfigValue,
  symbols: Record<string, KconfigSymbol>
): ConfigValue => {
  const newValues: ConfigValue = { ...currentValues };
  const symbol = symbols[symbolName];

  if (!symbol) return newValues;

  if (newValue === true || newValue === 'y' || newValue === 'm') {
    for (const dep of symbol.dependencies) {
      if (isFalsy(newValues[dep])) {
        newValues[dep] = 'y';
        const resolved = resolveDependencies(dep, 'y', newValues, symbols);
        Object.assign(newValues, resolved);
      }
    }

    for (const selected of symbol.selectedBy || []) {
      if (isFalsy(newValues[selected])) {
        newValues[selected] = 'y';
      }
    }
  } else if (newValue === false || newValue === 'n') {
    for (const [name, sym] of Object.entries(symbols)) {
      if (sym.dependencies.includes(symbolName)) {
        if (isTruthy(newValues[name])) {
          newValues[name] = 'n';
          const resolved = resolveDependencies(name, 'n', newValues, symbols);
          Object.assign(newValues, resolved);
        }
      }
    }
  }

  newValues[symbolName] = newValue;
  return newValues;
};

export function compareConfigs(
  current: ConfigValue,
  reference: ConfigValue,
  symbols: Record<string, KconfigSymbol>
): DiffResult {
  const allNames = new Set<string>([
    ...Object.keys(current),
    ...Object.keys(reference),
    ...Object.keys(symbols),
  ]);

  const items: DiffItem[] = [];
  let addedCount = 0;
  let removedCount = 0;
  let modifiedCount = 0;
  let unchangedCount = 0;

  const normalize = (v: string | boolean | number | undefined): string => {
    if (v === undefined) return 'undefined';
    if (v === true) return 'y';
    if (v === false) return 'n';
    return String(v);
  };

  for (const name of allNames) {
    const curVal = current[name];
    const refVal = reference[name];
    const curNorm = normalize(curVal);
    const refNorm = normalize(refVal);

    let type: DiffItem['type'];

    if (refVal === undefined && curVal !== undefined) {
      type = 'added';
      addedCount++;
    } else if (curVal === undefined && refVal !== undefined) {
      type = 'removed';
      removedCount++;
    } else if (curNorm !== refNorm) {
      type = 'modified';
      modifiedCount++;
    } else {
      type = 'unchanged';
      unchangedCount++;
    }

    items.push({
      name,
      type,
      currentValue: curVal,
      referenceValue: refVal,
    });
  }

  return { items, addedCount, removedCount, modifiedCount, unchangedCount };
}

export function generateMinimalConfig(
  values: ConfigValue,
  symbols: Record<string, KconfigSymbol>
): MinimalConfigResult {
  const enabledSet = new Set<string>();
  const isEnabled = (name: string): boolean => {
    const v = values[name];
    return v === true || v === 'y' || v === 'm';
  };

  function collectDeps(name: string, visited: Set<string>) {
    if (visited.has(name)) return;
    visited.add(name);
    enabledSet.add(name);
    const sym = symbols[name];
    if (!sym) return;
    for (const dep of sym.dependencies) {
      collectDeps(dep, visited);
    }
  }

  for (const name of Object.keys(values)) {
    if (isEnabled(name)) {
      collectDeps(name, new Set());
    }
  }

  const minimalValues: ConfigValue = {};
  const removedSymbols: string[] = [];

  for (const [name, value] of Object.entries(values)) {
    if (enabledSet.has(name)) {
      minimalValues[name] = value;
    } else {
      removedSymbols.push(name);
    }
  }

  const configLines: string[] = [];
  const now = new Date().toISOString();
  configLines.push(`# Minimal config - generated by Kconfig Web Editor`);
  configLines.push(`# Date: ${now}`);
  configLines.push(`# Only includes enabled options and their dependencies`);
  configLines.push('');

  for (const [name, sym] of Object.entries(symbols)) {
    const value = minimalValues[name];
    if (value === undefined) continue;
    if (value === false || value === 'n') {
      configLines.push(`# CONFIG_${name} is not set`);
    } else if (value === true || value === 'y') {
      configLines.push(`CONFIG_${name}=y`);
    } else if (value === 'm') {
      configLines.push(`CONFIG_${name}=m`);
    } else if (sym.type === 'string') {
      configLines.push(`CONFIG_${name}="${value}"`);
    } else {
      configLines.push(`CONFIG_${name}=${value}`);
    }
  }

  configLines.push('');

  return {
    values: minimalValues,
    removedCount: removedSymbols.length,
    keptCount: Object.keys(minimalValues).length,
    removedSymbols,
    config: configLines.join('\n'),
  };
}

export const generateConfig = generateConfigContent;
