const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

function runSimulation(netlist, timeoutMs = 15000) {
  return new Promise((resolve, reject) => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spice-'));
    const inputFile = path.join(tmpDir, 'circuit.cir');
    const outputFile = path.join(tmpDir, 'output.raw');
    const logFile = path.join(tmpDir, 'log.txt');

    fs.writeFileSync(inputFile, netlist);

    let ngspicePath = 'ngspice';
    if (process.platform === 'darwin') {
      ngspicePath = '/opt/local/bin/ngspice';
      if (!fs.existsSync(ngspicePath)) {
        ngspicePath = '/usr/local/bin/ngspice';
      }
      if (!fs.existsSync(ngspicePath)) {
        ngspicePath = 'ngspice';
      }
    }

    const args = ['-b', '-r', outputFile, '-o', logFile, inputFile];

    let stderr = '';
    let stdout = '';
    let killed = false;
    let convergenceError = null;

    const convergenceKeywords = [
      'convergence',
      'iterations',
      'singular matrix',
      'timestep too small',
      'fatal error',
      'error:',
      'failed'
    ];

    const proc = spawn(ngspicePath, args, { cwd: tmpDir });

    const timer = setTimeout(() => {
      if (!killed) {
        killed = true;
        proc.kill('SIGKILL');
        cleanup();
        let msg = `Simulation timed out after ${timeoutMs / 1000}s`;
        if (convergenceError) {
          msg += ` - ${convergenceError}`;
        }
        reject(new Error(msg));
      }
    }, timeoutMs);

    function cleanup() {
      clearTimeout(timer);
      try {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      } catch (e) {
        console.warn('Cleanup failed:', e.message);
      }
    }

    function checkConvergence(text) {
      if (convergenceError) return;
      const lower = text.toLowerCase();
      for (const kw of convergenceKeywords) {
        if (lower.includes(kw)) {
          const lines = text.split('\n').filter(l => l.toLowerCase().includes(kw)).slice(0, 3);
          convergenceError = lines.join('; ') || `Detected "${kw}" in output`;
          return;
        }
      }
    }

    proc.stdout.on('data', (data) => {
      const str = data.toString();
      stdout += str;
      checkConvergence(str);
    });

    proc.stderr.on('data', (data) => {
      const str = data.toString();
      stderr += str;
      checkConvergence(str);
    });

    proc.on('error', (err) => {
      if (killed) return;
      killed = true;
      cleanup();
      if (err.code === 'ENOENT') {
        reject(new Error('Ngspice not found. Please install ngspice: brew install ngspice or apt-get install ngspice'));
      } else {
        reject(err);
      }
    });

    proc.on('close', (code) => {
      if (killed) return;
      clearTimeout(timer);

      let logContent = '';
      try {
        if (fs.existsSync(logFile)) {
          logContent = fs.readFileSync(logFile, 'utf8');
          checkConvergence(logContent);
        }
      } catch (e) {}

      if (code !== 0 || convergenceError) {
        cleanup();
        let msg = convergenceError || `Ngspice exited with code ${code}`;
        const lastLines = (stdout + '\n' + stderr + '\n' + logContent)
          .split('\n')
          .filter(l => l.trim())
          .slice(-10)
          .join('\n');
        reject(new Error(`${msg}\n\nLast output:\n${lastLines}`));
        return;
      }

      try {
        if (!fs.existsSync(outputFile)) {
          cleanup();
          reject(new Error('No output generated by ngspice. Check circuit for errors.'));
          return;
        }
        const rawData = fs.readFileSync(outputFile);
        const result = parseRawFile(rawData);
        cleanup();
        resolve(result);
      } catch (e) {
        cleanup();
        reject(e);
      }
    });
  });
}

function parseRawFile(buffer) {
  let offset = 0;
  const decoder = new TextDecoder('utf-8');

  function readLine() {
    let end = offset;
    while (end < buffer.length && buffer[end] !== 0x0a) end++;
    const line = decoder.decode(buffer.slice(offset, end));
    offset = end + 1;
    return line;
  }

  const header = {};
  let line = readLine();

  while (line !== 'Values:') {
    if (line.startsWith('Title:')) {
      header.title = line.slice(6).trim();
    } else if (line.startsWith('Date:')) {
      header.date = line.slice(5).trim();
    } else if (line.startsWith('Plotname:')) {
      header.plotname = line.slice(8).trim();
    } else if (line.startsWith('Flags:')) {
      header.flags = line.slice(6).trim().split(/\s+/);
    } else if (line.startsWith('No. Variables:')) {
      header.numVars = parseInt(line.slice(14));
    } else if (line.startsWith('No. Points:')) {
      header.numPoints = parseInt(line.slice(11));
    } else if (line.startsWith('Variables:')) {
      header.variables = [];
      for (let i = 0; i < header.numVars; i++) {
        const varLine = readLine();
        const parts = varLine.trim().split(/\s+/);
        header.variables.push({
          index: parseInt(parts[0]),
          name: parts[1],
          type: parts[2]
        });
      }
    }
    line = readLine();
  }

  const isComplex = header.flags && header.flags.includes('complex');
  const isTransient = header.plotname === 'Transient Analysis';

  const data = {};
  header.variables.forEach(v => {
    data[v.name] = [];
  });

  if (isComplex) {
    const pointSize = 4 + header.numVars * 16;
    for (let i = 0; i < header.numPoints; i++) {
      if (offset + 4 > buffer.length) break;
      const idx = buffer.readInt32LE(offset);
      offset += 4;
      for (const v of header.variables) {
        if (offset + 16 > buffer.length) break;
        const real = buffer.readDoubleLE(offset);
        const imag = buffer.readDoubleLE(offset + 8);
        offset += 16;
        data[v.name].push({ real, imag });
      }
    }
  } else {
    const pointSize = 4 + header.numVars * 8;
    for (let i = 0; i < header.numPoints; i++) {
      if (offset + 4 > buffer.length) break;
      const idx = buffer.readInt32LE(offset);
      offset += 4;
      for (const v of header.variables) {
        if (offset + 8 > buffer.length) break;
        const val = buffer.readDoubleLE(offset);
        offset += 8;
        data[v.name].push(val);
      }
    }
  }

  return {
    header,
    data,
    isComplex,
    isTransient
  };
}

module.exports = {
  runSimulation,
  parseRawFile
};
