import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate, Link, useParams } from 'react-router-dom';
import {
  ArrowLeft, Save, Eye, Rocket, Trash2, Copy, Download,
  FileCode, AlertCircle, CheckCircle, Loader2, Settings,
  Package, Globe, Bug, Github, Mail, Calendar
} from 'lucide-react';
import { Navbar } from '../components/Navbar';
import { developmentService, pluginService } from '../services/plugins';
import { useAuthStore } from '../store/authStore';

interface DraftData {
  id?: string;
  name: string;
  version: string;
  description: string;
  about: string;
  author: string;
  email: string;
  qgisMinimumVersion: string;
  qgisMaximumVersion: string;
  homepage: string;
  tracker: string;
  repository: string;
  category: string;
  icon: string;
  license: string;
  deprecated: boolean;
  experimental: boolean;
  tags: string;
  changelog: string;
  dependencies: string;
}

const defaultDraft: DraftData = {
  name: '',
  version: '0.1.0',
  description: '',
  about: '',
  author: '',
  email: '',
  qgisMinimumVersion: '3.0',
  qgisMaximumVersion: '',
  homepage: '',
  tracker: '',
  repository: '',
  category: '',
  icon: '',
  license: '',
  deprecated: false,
  experimental: false,
  tags: '',
  changelog: '',
  dependencies: '',
};

export const PluginDevelopment: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user, isAuthenticated } = useAuthStore();
  const [activeTab, setActiveTab] = useState<'form' | 'metadata'>('form');
  const [draft, setDraft] = useState<DraftData>(defaultDraft);
  const [categories, setCategories] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [metadataPreview, setMetadataPreview] = useState('');

  const loadCategories = useCallback(async () => {
    try {
      const result = await pluginService.getCategories();
      if (result.success && result.data) {
        setCategories(result.data.map((c: any) => c.name));
      }
    } catch (err) {
      console.error('Failed to load categories:', err);
    }
  }, []);

  const loadDraft = useCallback(async () => {
    if (!id) {
      setLoading(false);
      return;
    }

    try {
      const result = await pluginService.getPlugin(id);
      if (result.success && result.data) {
        const plugin = result.data;
        setDraft({
          id: plugin.id,
          name: plugin.name,
          version: plugin.versions?.[0]?.version || '0.1.0',
          description: plugin.description,
          about: '',
          author: plugin.author,
          email: plugin.email || '',
          qgisMinimumVersion: plugin.qgisMinVersion,
          qgisMaximumVersion: plugin.qgisMaxVersion || '',
          homepage: plugin.homepage || '',
          tracker: plugin.tracker || '',
          repository: plugin.repository || '',
          category: plugin.category?.name || '',
          icon: plugin.icon || '',
          license: plugin.license || '',
          deprecated: plugin.deprecated,
          experimental: plugin.experimental,
          tags: '',
          changelog: '',
          dependencies: plugin.dependencies?.map((d: any) => d.dependencyName).join(', ') || '',
        });
      }
    } catch (err) {
      console.error('Failed to load draft:', err);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login');
      return;
    }
    loadCategories();
    loadDraft();
  }, [isAuthenticated, navigate, loadCategories, loadDraft]);

  const generateMetadataTxt = (): string => {
    const lines: string[] = [];
    lines.push('; QGIS Plugin Metadata');
    lines.push('; Generated by QGIS Plugin Repository');
    lines.push('');
    lines.push(`[general]`);
    lines.push(`name=${draft.name}`);
    lines.push(`version=${draft.version}`);
    lines.push(`description=${draft.description}`);
    if (draft.about) lines.push(`about=${draft.about}`);
    lines.push(`author=${draft.author}`);
    if (draft.email) lines.push(`email=${draft.email}`);
    lines.push(`qgisMinimumVersion=${draft.qgisMinimumVersion}`);
    if (draft.qgisMaximumVersion) lines.push(`qgisMaximumVersion=${draft.qgisMaximumVersion}`);
    if (draft.homepage) lines.push(`homepage=${draft.homepage}`);
    if (draft.tracker) lines.push(`tracker=${draft.tracker}`);
    if (draft.repository) lines.push(`repository=${draft.repository}`);
    if (draft.category) lines.push(`category=${draft.category}`);
    if (draft.icon) lines.push(`icon=${draft.icon}`);
    if (draft.license) lines.push(`license=${draft.license}`);
    lines.push(`deprecated=${draft.deprecated ? 'True' : 'False'}`);
    lines.push(`experimental=${draft.experimental ? 'True' : 'False'}`);
    if (draft.tags) lines.push(`tags=${draft.tags}`);
    if (draft.changelog) lines.push(`changelog=${draft.changelog}`);
    if (draft.dependencies) lines.push(`dependencies=${draft.dependencies}`);
    return lines.join('\n');
  };

  const updateMetadataPreview = useCallback(() => {
    setMetadataPreview(generateMetadataTxt());
  }, [draft]);

  useEffect(() => {
    if (activeTab === 'metadata') {
      updateMetadataPreview();
    }
  }, [activeTab, updateMetadataPreview]);

  const handleChange = (field: keyof DraftData, value: string | boolean) => {
    setDraft((prev) => ({ ...prev, [field]: value }));
    setMessage(null);
  };

  const handleSave = async () => {
    if (!draft.name || !draft.version || !draft.description || !draft.author || !draft.qgisMinimumVersion) {
      setMessage({ type: 'error', text: '请填写所有必填字段（名称、版本、描述、作者、QGIS最低版本）' });
      return;
    }

    setSaving(true);
    setMessage(null);

    try {
      if (draft.id) {
        const result = await developmentService.updateDraft(draft.id, draft);
        if (result.success) {
          setMessage({ type: 'success', text: '草稿保存成功！' });
        } else {
          throw new Error(result.error || '保存失败');
        }
      } else {
        const result = await developmentService.createDraft(draft);
        if (result.success && result.data) {
          setDraft((prev) => ({ ...prev, id: result.data!.id }));
          setMessage({ type: 'success', text: '草稿创建成功！' });
        } else {
          throw new Error(result.error || '创建失败');
        }
      }
    } catch (err) {
      setMessage({ type: 'error', text: (err as Error).message });
    } finally {
      setSaving(false);
    }
  };

  const handlePublish = async () => {
    if (!draft.id) {
      setMessage({ type: 'error', text: '请先保存草稿' });
      return;
    }

    if (!confirm('发布后插件将在仓库中可见，确定要发布吗？')) {
      return;
    }

    setPublishing(true);
    setMessage(null);

    try {
      const result = await developmentService.publishDraft(draft.id);
      if (result.success) {
        setMessage({ type: 'success', text: '插件发布成功！' });
        setTimeout(() => {
          navigate(`/plugins/${draft.id}`);
        }, 2000);
      } else {
        throw new Error(result.error || '发布失败');
      }
    } catch (err) {
      setMessage({ type: 'error', text: (err as Error).message });
    } finally {
      setPublishing(false);
    }
  };

  const handleCopyMetadata = () => {
    const metadata = generateMetadataTxt();
    navigator.clipboard.writeText(metadata);
    setMessage({ type: 'success', text: 'metadata.txt 已复制到剪贴板！' });
  };

  const handleDownloadMetadata = () => {
    const metadata = generateMetadataTxt();
    const blob = new Blob([metadata], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'metadata.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-teal-500 animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-900">
      <Navbar />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-slate-400 hover:text-white mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          返回插件列表
        </Link>

        <div className="bg-gradient-to-r from-slate-800/50 to-slate-800/30 backdrop-blur-sm border border-slate-700/50 rounded-2xl p-8 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-gradient-to-br from-teal-500/20 to-blue-500/20 rounded-xl flex items-center justify-center border border-teal-500/30">
                <FileCode className="w-6 h-6 text-teal-400" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">
                  {id ? '编辑插件' : '创建新插件'}
                </h1>
                <p className="text-slate-400 text-sm">
                  {id ? '修改插件元数据' : '填写插件信息并创建草稿'}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={handleSave}
                disabled={saving}
                className="inline-flex items-center gap-2 px-5 py-2.5 bg-slate-700 text-white font-medium rounded-lg hover:bg-slate-600 transition-colors disabled:opacity-50"
              >
                <Save className="w-5 h-5" />
                {saving ? '保存中...' : '保存草稿'}
              </button>
              {draft.id && (
                <button
                  onClick={handlePublish}
                  disabled={publishing}
                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-teal-500 to-blue-500 text-white font-medium rounded-lg hover:from-teal-600 hover:to-blue-600 transition-all disabled:opacity-50"
                >
                  <Rocket className="w-5 h-5" />
                  {publishing ? '发布中...' : '发布'}
                </button>
              )}
            </div>
          </div>

          {message && (
            <div
              className={`flex items-center gap-3 p-4 rounded-lg mb-6 ${
                message.type === 'success'
                  ? 'bg-green-500/10 border border-green-500/30 text-green-400'
                  : 'bg-red-500/10 border border-red-500/30 text-red-400'
              }`}
            >
              {message.type === 'success' ? (
                <CheckCircle className="w-5 h-5" />
              ) : (
                <AlertCircle className="w-5 h-5" />
              )}
              {message.text}
            </div>
          )}

          <div className="flex border-b border-slate-700 mb-6">
            <button
              onClick={() => setActiveTab('form')}
              className={`px-6 py-3 font-medium transition-colors ${
                activeTab === 'form'
                  ? 'text-teal-400 border-b-2 border-teal-400'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Settings className="w-4 h-4 inline mr-2" />
              表单编辑
            </button>
            <button
              onClick={() => setActiveTab('metadata')}
              className={`px-6 py-3 font-medium transition-colors ${
                activeTab === 'metadata'
                  ? 'text-teal-400 border-b-2 border-teal-400'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <FileCode className="w-4 h-4 inline mr-2" />
              metadata.txt 预览
            </button>
          </div>

          {activeTab === 'form' ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Package className="w-5 h-5 text-teal-400" />
                    基本信息
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        插件名称 <span className="text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        value={draft.name}
                        onChange={(e) => handleChange('name', e.target.value)}
                        placeholder="My Plugin"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        版本号 <span className="text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        value={draft.version}
                        onChange={(e) => handleChange('version', e.target.value)}
                        placeholder="1.0.0"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        描述 <span className="text-red-400">*</span>
                      </label>
                      <textarea
                        value={draft.description}
                        onChange={(e) => handleChange('description', e.target.value)}
                        placeholder="Brief description of the plugin"
                        rows={3}
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors resize-none"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        详细介绍 (about)
                      </label>
                      <textarea
                        value={draft.about}
                        onChange={(e) => handleChange('about', e.target.value)}
                        placeholder="Detailed description..."
                        rows={4}
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors resize-none"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Mail className="w-5 h-5 text-teal-400" />
                    作者信息
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        作者 <span className="text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        value={draft.author}
                        onChange={(e) => handleChange('author', e.target.value)}
                        placeholder="Your Name"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        邮箱
                      </label>
                      <input
                        type="email"
                        value={draft.email}
                        onChange={(e) => handleChange('email', e.target.value)}
                        placeholder="email@example.com"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Settings className="w-5 h-5 text-teal-400" />
                    QGIS 版本
                  </h3>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        最低版本 <span className="text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        value={draft.qgisMinimumVersion}
                        onChange={(e) => handleChange('qgisMinimumVersion', e.target.value)}
                        placeholder="3.0"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        最高版本
                      </label>
                      <input
                        type="text"
                        value={draft.qgisMaximumVersion}
                        onChange={(e) => handleChange('qgisMaximumVersion', e.target.value)}
                        placeholder="3.99"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Globe className="w-5 h-5 text-teal-400" />
                    链接和分类
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        分类
                      </label>
                      <select
                        value={draft.category}
                        onChange={(e) => handleChange('category', e.target.value)}
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-teal-500 transition-colors"
                      >
                        <option value="">选择分类</option>
                        {categories.map((cat) => (
                          <option key={cat} value={cat}>
                            {cat}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        项目主页
                      </label>
                      <input
                        type="url"
                        value={draft.homepage}
                        onChange={(e) => handleChange('homepage', e.target.value)}
                        placeholder="https://example.com"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        <Bug className="w-4 h-4 inline mr-1" />
                        问题追踪
                      </label>
                      <input
                        type="url"
                        value={draft.tracker}
                        onChange={(e) => handleChange('tracker', e.target.value)}
                        placeholder="https://github.com/..."
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        <Github className="w-4 h-4 inline mr-1" />
                        代码仓库
                      </label>
                      <input
                        type="url"
                        value={draft.repository}
                        onChange={(e) => handleChange('repository', e.target.value)}
                        placeholder="https://github.com/..."
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Settings className="w-5 h-5 text-teal-400" />
                    高级设置
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        许可证
                      </label>
                      <select
                        value={draft.license}
                        onChange={(e) => handleChange('license', e.target.value)}
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-teal-500 transition-colors"
                      >
                        <option value="">选择许可证</option>
                        <option value="GPL-2.0">GPL-2.0</option>
                        <option value="GPL-3.0">GPL-3.0</option>
                        <option value="MIT">MIT</option>
                        <option value="BSD-3-Clause">BSD-3-Clause</option>
                        <option value="Apache-2.0">Apache-2.0</option>
                        <option value="LGPL-3.0">LGPL-3.0</option>
                      </select>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={draft.experimental}
                          onChange={(e) => handleChange('experimental', e.target.checked)}
                          className="w-4 h-4 text-teal-500 bg-slate-700 border-slate-600 rounded focus:ring-teal-500"
                        />
                        <span className="text-sm text-slate-300">实验性</span>
                      </label>
                      <label className="flex items-center gap-3 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={draft.deprecated}
                          onChange={(e) => handleChange('deprecated', e.target.checked)}
                          className="w-4 h-4 text-teal-500 bg-slate-700 border-slate-600 rounded focus:ring-teal-500"
                        />
                        <span className="text-sm text-slate-300">已弃用</span>
                      </label>
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        标签 (逗号分隔)
                      </label>
                      <input
                        type="text"
                        value={draft.tags}
                        onChange={(e) => handleChange('tags', e.target.value)}
                        placeholder="analysis, tools, vector"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-slate-300 mb-2">
                        依赖 (逗号分隔)
                      </label>
                      <input
                        type="text"
                        value={draft.dependencies}
                        onChange={(e) => handleChange('dependencies', e.target.value)}
                        placeholder="plugin1, plugin2"
                        className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py--2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-teal-400" />
                    更新日志
                  </h3>
                  <textarea
                    value={draft.changelog}
                    onChange={(e) => handleChange('changelog', e.target.value)}
                    placeholder="Version 1.0.0:&#10;- Initial release"
                    rows={4}
                    className="w-full px-4 py-2.5 bg-slate-700/50 border border-slate-600 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-teal-500 transition-colors resize-none"
                  />
                </div>
              </div>
            </div>
          ) : (
            <div>
              <div className="flex items-center justify-between mb-4">
                <p className="text-sm text-slate-400">预览生成的 metadata.txt 文件内容</p>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopyMetadata}
                    className="inline-flex items-center gap-1 px-3 py-1.5 bg-slate-700 text-slate-300 text-sm rounded-lg hover:bg-slate-600 transition-colors"
                  >
                    <Copy className="w-4 h-4" />
                    复制
                  </button>
                  <button
                    onClick={handleDownloadMetadata}
                    className="inline-flex items-center gap-1 px-3 py-1.5 bg-slate-700 text-slate-300 text-sm rounded-lg hover:bg-slate-600 transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    下载
                  </button>
                </div>
              </div>
              <pre className="bg-slate-900/50 border border-slate-700 rounded-lg p-4 text-sm text-slate-300 overflow-x-auto">
                <code>{metadataPreview}</code>
              </pre>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};
