#!/usr/bin/env python3
import os
BASE = '/Users/wuwenbo/Documents/trae_projects/SoloProjects-hll/p201'

# ConfigTree.tsx
tree_content = "import { useRef, useEffect, useState, useCallback, useMemo } from 'react';\n"
tree_content += "import { useKconfigStore } from '@/store/kconfigStore';\n"
tree_content += "import { ConfigTreeRow } from './ConfigTreeRow';\n"
tree_content += "import { FileWarning } from 'lucide-react';\n\n"
tree_content += "const ROW_HEIGHT = 34;\n"
tree_content += "const OVERSCAN = 8;\n\n"
tree_content += "export function ConfigTree() {\n"
tree_content += "  const loaded = useKconfigStore((s) => s.loaded);\n"
tree_content += "  const tree = useKconfigStore((s) => s.tree);\n"
tree_content += "  const expandedNodes = useKconfigStore((s) => s.expandedNodes);\n"
tree_content += "  const searchQuery = useKconfigStore((s) => s.searchQuery);\n"
tree_content += "  const values = useKconfigStore((s) => s.values);\n"
tree_content += "  const getFlatItems = useKconfigStore((s) => s.getFlatItems);\n\n"
tree_content += "  const containerRef = useRef<HTMLDivElement>(null);\n"
tree_content += "  const [scrollTop, setScrollTop] = useState(0);\n"
tree_content += "  const [containerHeight, setContainerHeight] = useState(0);\n\n"
tree_content += "  const flatItems = useMemo(() => getFlatItems(), [tree, expandedNodes, searchQuery, values]);\n"
tree_content += "  const totalCount = flatItems.length;\n"
tree_content += "  const totalHeight = totalCount * ROW_HEIGHT;\n\n"
tree_content += "  const startIndex = Math.max(0, Math.floor(scrollTop / ROW_HEIGHT) - OVERSCAN);\n"
tree_content += "  const endIndex = Math.min(totalCount - 1, Math.ceil((scrollTop + containerHeight) / ROW_HEIGHT) + OVERSCAN);\n"
tree_content += "  const visibleItems = flatItems.slice(startIndex, endIndex + 1);\n\n"
tree_content += "  const handleScroll = useCallback(() => {\n"
tree_content += "    if (containerRef.current) setScrollTop(containerRef.current.scrollTop);\n"
tree_content += "  }, []);\n\n"
tree_content += "  useEffect(() => {\n"
tree_content += "    const el = containerRef.current;\n"
tree_content += "    if (!el) return;\n"
tree_content += "    const observer = new ResizeObserver((entries) => {\n"
tree_content += "      for (const entry of entries) setContainerHeight(entry.contentRect.height);\n"
tree_content += "    });\n"
tree_content += "    observer.observe(el);\n"
tree_content += "    setContainerHeight(el.clientHeight);\n"
tree_content += "    return () => observer.disconnect();\n"
tree_content += "  }, []);\n\n"
tree_content += "  if (!loaded) {\n"
tree_content += "    return (\n"
tree_content += "      <div className=\"flex flex-col items-center justify-center h-full text-gray-500\">\n"
tree_content += "        <FileWarning className=\"w-16 h-16 mb-4 opacity-50\" />\n"
tree_content += "        <p className=\"text-lg font-mono\">No Kconfig loaded</p>\n"
tree_content += "        <p className=\"text-sm mt-2\">Upload a Kconfig file or load a sample</p>\n"
tree_content += "      </div>\n"
tree_content += "    );\n"
tree_content += "  }\n\n"
tree_content += "  return (\n"
tree_content += "    <div ref={containerRef} className=\"h-full overflow-y-auto\" onScroll={handleScroll}>\n"
tree_content += "      <div style={{ height: totalHeight, position: 'relative' }}>\n"
tree_content += "        {visibleItems.map((item, idx) => (\n"
tree_content += "          <ConfigTreeRow key={item.nodeId} node={item.node} level={item.level} top={(startIndex + idx) * ROW_HEIGHT} />\n"
tree_content += "        ))}\n"
tree_content += "      </div>\n"
tree_content += "    </div>\n"
tree_content += "  );\n"
tree_content += "}\n"

with open(os.path.join(BASE, 'src/components/ConfigTree.tsx'), 'w') as f:
    f.write(tree_content)
print('Written ConfigTree.tsx')
