from config import Config
from collections import defaultdict

class NetlistGenerator:
    def __init__(self):
        self.comp_counters = defaultdict(int)
    
    def generate_netlist(self, circuit_graph, components_data):
        lines = []
        lines.append("* SPICE Netlist - Generated by Circuit OCR")
        lines.append("* " + "="*50)
        lines.append("")
        
        node_mapping = self._assign_nodes(circuit_graph, components_data)
        
        for comp_id, comp_info in components_data.items():
            comp_type = comp_info.get('type', 'UNKNOWN')
            spice_line = self._generate_component_line(
                comp_id, comp_type, comp_info, node_mapping, circuit_graph
            )
            if spice_line:
                lines.append(spice_line)
        
        lines.append("")
        lines.append(f"Vcc Vcc 0 DC {Config.SPICE_VOLTAGE}")
        lines.append("")
        lines.append(".END")
        
        return "\n".join(lines)
    
    def _assign_nodes(self, circuit_graph, components_data):
        node_mapping = {}
        node_counter = 1
        
        for comp_id in components_data.keys():
            connections = circuit_graph.get_component_connections(comp_id)
            for conn in connections:
                connected_to = conn['connected_to']
                key = tuple(sorted([str(comp_id), str(connected_to)]))
                if key not in node_mapping:
                    node_mapping[key] = f"{node_counter}"
                    node_counter += 1
        
        return node_mapping
    
    def _generate_component_line(self, comp_id, comp_type, comp_info, node_mapping, circuit_graph):
        self.comp_counters[comp_type] += 1
        counter = self.comp_counters[comp_type]
        
        connections = circuit_graph.get_component_connections(comp_id)
        
        if len(connections) >= 2:
            nodes = []
            for conn in connections[:2]:
                key = tuple(sorted([str(comp_id), str(conn['connected_to'])]))
                nodes.append(node_mapping.get(key, '0'))
        else:
            nodes = ['0', '0']
        
        value = self._extract_value(comp_info.get('text', ''), comp_type)
        
        if comp_type == 'RESISTOR':
            return f"R{counter} {nodes[0]} {nodes[1]} {value}"
        elif comp_type == 'CAPACITOR':
            return f"C{counter} {nodes[0]} {nodes[1]} {value}"
        elif comp_type == 'IC':
            pin_count = comp_info.get('pin_count', 8)
            pin_nodes = ' '.join([str(i) for i in range(pin_count)])
            return f"X{counter} {pin_nodes} IC_{counter}"
        else:
            return f"* Unknown component {comp_id}: {comp_type}"
    
    def _extract_value(self, text, comp_type):
        import re
        
        text = text.upper().strip()
        
        if comp_type == 'RESISTOR':
            match = re.search(r'(\d+\.?\d*\s*(K|M|KILOHM|OHM)?)', text)
            if match:
                val = match.group(1)
                if 'K' in val.upper():
                    num = re.search(r'(\d+\.?\d*)', val).group(1)
                    return f"{num}k"
                elif 'M' in val.upper():
                    num = re.search(r'(\d+\.?\d*)', val).group(1)
                    return f"{num}MEG"
                else:
                    num = re.search(r'(\d+\.?\d*)', val)
                    if num:
                        return f"{num.group(1)}"
            return "1k"
        
        elif comp_type == 'CAPACITOR':
            match = re.search(r'(\d+\.?\d*\s*(U|N|P|UF|NF|PF)?)', text)
            if match:
                val = match.group(1)
                if 'U' in val.upper():
                    num = re.search(r'(\d+\.?\d*)', val).group(1)
                    return f"{num}u"
                elif 'N' in val.upper():
                    num = re.search(r'(\d+\.?\d*)', val).group(1)
                    return f"{num}n"
                elif 'P' in val.upper():
                    num = re.search(r'(\d+\.?\d*)', val).group(1)
                    return f"{num}p"
                else:
                    num = re.search(r'(\d+\.?\d*)', val)
                    if num:
                        return f"{num.group(1)}u"
            return "1u"
        
        return "1k"
    
    def generate_detailed_netlist(self, circuit_graph, components_data):
        netlist = self.generate_netlist(circuit_graph, components_data)
        
        detailed = []
        detailed.append("* " + "="*60)
        detailed.append("* DETAILED COMPONENT INFORMATION")
        detailed.append("* " + "="*60)
        detailed.append("")
        
        for comp_id, comp_info in components_data.items():
            detailed.append(f"* Component: {comp_id}")
            detailed.append(f"*   Type: {comp_info.get('type', 'UNKNOWN')}")
            detailed.append(f"*   Confidence: {comp_info.get('confidence', 0):.2f}")
            detailed.append(f"*   OCR Text: {comp_info.get('text', 'N/A')}")
            detailed.append(f"*   Position: ({comp_info.get('x', 0)}, {comp_info.get('y', 0)})")
            detailed.append(f"*   Size: {comp_info.get('width', 0)}x{comp_info.get('height', 0)}")
            detailed.append("")
        
        detailed.append("* " + "="*60)
        detailed.append("")
        detailed.append(netlist)
        
        return "\n".join(detailed)
