from __future__ import annotations
from models import RuleResult

RULES_REGISTRY = [
    {"id": "ST-001", "category": "SegmentTemplate", "severity": "error", "description": "SegmentTemplate must have media attribute or SegmentTimeline child", "spec_ref": "DASH-IF IOP v5.0 §4.4.2", "check": "Verify that each SegmentTemplate element has either a `media` attribute or a `SegmentTimeline` child element. If both are missing, the SegmentTemplate cannot resolve segment URLs."},
    {"id": "ST-002", "category": "SegmentTemplate", "severity": "error", "description": "Template identifiers in media must be consistent with index attribute", "spec_ref": "DASH-IF IOP v5.0 §4.4.2", "check": "If SegmentTemplate@index='number', the `media` template must contain `$Number$`. If @index='time', it must contain `$Time$`. Mismatches cause playback failures."},
    {"id": "ST-003", "category": "SegmentTemplate", "severity": "warning", "description": "initialization attribute should not contain $Number$ or $Time$", "spec_ref": "DASH-IF IOP v5.0 §4.4.2", "check": "The initialization segment is a shared resource for all segments in a Representation. Including `$Number$` or `$Time$` in the initialization URL template is likely an error."},
    {"id": "ST-004", "category": "SegmentTemplate", "severity": "error", "description": "timescale when explicitly set must be a positive integer", "spec_ref": "ISO 23009-1 §5.3.9.5.2", "check": "The `timescale` attribute specifies the number of time units per second. It must be a positive integer. The default value is 1."},
    {"id": "ST-005", "category": "SegmentTemplate", "severity": "error", "description": "startNumber should be a non-negative integer", "spec_ref": "ISO 23009-1 §5.3.9.5.2", "check": "The `startNumber` attribute defines the first segment number. It must be a non-negative integer (≥ 0)."},
    {"id": "ST-006", "category": "SegmentTemplate", "severity": "error", "description": "SegmentTimeline t and d attributes must be non-negative integers", "spec_ref": "ISO 23009-1 §5.3.9.5.2", "check": "In SegmentTimeline, `S@d` (duration) and `S@t` (time) attributes must be non-negative integer values in timescale units."},
    {"id": "TS-001", "category": "Timing/Timescale", "severity": "error", "description": "MPD@mediaPresentationDuration must exist in static MPD", "spec_ref": "ISO 23009-1 §5.3.1.1", "check": "For static MPD presentations, `mediaPresentationDuration` is required to inform the client of the total presentation length."},
    {"id": "TS-002", "category": "Timing/Timescale", "severity": "error", "description": "Period duration or start must be valid ISO 8601 duration format", "spec_ref": "ISO 23009-1 §5.3.2.1", "check": "Period `duration` and `start` attributes must conform to the ISO 8601 duration format (e.g., PT30S, PT1H30M15.5S)."},
    {"id": "TS-003", "category": "Timing/Timescale", "severity": "warning", "description": "SegmentTemplate duration/timescale should roughly match Period duration", "spec_ref": "DASH-IF IOP v5.0 §4.5", "check": "The segment duration computed from `SegmentTemplate@duration / timescale` should be consistent with the Period duration. A deviation > 50% indicates a likely configuration error."},
    {"id": "TS-004", "category": "Timing/Timescale", "severity": "error", "description": "minimumUpdatePeriod must exist in dynamic MPD", "spec_ref": "ISO 23009-1 §5.3.1.1", "check": "For dynamic MPD presentations, `minimumUpdatePeriod` is required to inform the client how often to refresh the MPD."},
    {"id": "TS-005", "category": "Timing/Timescale", "severity": "warning", "description": "Segment duration should yield integer milliseconds", "spec_ref": "DASH-IF IOP v5.0 §4.5 / ISO 23009-1", "check": "For precise segment alignment, `(duration × 1000) / timescale` should yield an integer number of milliseconds. Non-integer millisecond values may cause timing drift or rounding issues in players."},
    {"id": "RP-001", "category": "Representation", "severity": "error", "description": "Each Representation must have bandwidth attribute and it must be a positive integer", "spec_ref": "ISO 23009-1 §5.3.1.2", "check": "The `bandwidth` attribute is required on every Representation. It specifies the peak bitrate in bits per second and must be a positive integer."},
    {"id": "RP-002", "category": "Representation", "severity": "error", "description": "Each Representation must have id attribute", "spec_ref": "ISO 23009-1 §5.3.1.2", "check": "The `id` attribute uniquely identifies a Representation within its Period. It is required for client adaptation logic."},
    {"id": "RP-003", "category": "Representation", "severity": "warning", "description": "Video Representation should contain width, height, frameRate attributes", "spec_ref": "DASH-IF IOP v5.0 §4.2", "check": "Video Representations should declare `width`, `height`, and `frameRate` to enable proper codec initialization and adaptive streaming decisions."},
    {"id": "RP-004", "category": "Representation", "severity": "warning", "description": "Audio Representation should contain audioSamplingRate attribute", "spec_ref": "DASH-IF IOP v5.0 §4.2", "check": "Audio Representations should declare `audioSamplingRate` to enable proper audio decoder initialization."},
    {"id": "RP-005", "category": "Representation", "severity": "error", "description": "codecs must exist at AdaptationSet or Representation level", "spec_ref": "DASH-IF IOP v5.0 §4.2 / ISO 23009-1 §5.3.1.2", "check": "The `codecs` attribute is required at either the AdaptationSet or Representation level. It describes the media codec and is essential for client codec selection."},
    {"id": "RP-006", "category": "Representation", "severity": "error", "description": "mimeType must exist at AdaptationSet or Representation level", "spec_ref": "ISO 23009-1 §5.3.1.2", "check": "The `mimeType` attribute (e.g., 'video/mp4' or 'audio/mp4') is required at either the AdaptationSet or Representation level."},
    {"id": "PD-001", "category": "Period/Structure", "severity": "error", "description": "MPD must have at least one Period element", "spec_ref": "ISO 23009-1 §5.3.1.1", "check": "An MPD document must contain at least one Period element. The Period is the fundamental structural unit of a DASH presentation."},
    {"id": "PD-002", "category": "Period/Structure", "severity": "error", "description": "Subsequent Periods must have start or previous Period must have duration", "spec_ref": "ISO 23009-1 §5.3.2.1", "check": "In multi-Period MPDs, each Period after the first must either have a `start` attribute or the preceding Period must have a `duration` attribute to ensure continuous playback."},
    {"id": "PD-003", "category": "Period/Structure", "severity": "error", "description": "AdaptationSet must contain at least one Representation", "spec_ref": "ISO 23009-1 §5.3.3.1", "check": "Each AdaptationSet must contain at least one Representation. An empty AdaptationSet provides no playable content."},
    {"id": "PD-004", "category": "Period/Structure", "severity": "error", "description": "ContentProtection must have schemeIdUri attribute", "spec_ref": "ISO 23009-1 §5.3.7.1", "check": "Every ContentProtection element must have a `schemeIdUri` attribute that identifies the protection system (e.g., 'urn:mpeg:dash:mp4protection:2011')."},
    {"id": "IOP-001", "category": "DASH-IF IOP", "severity": "warning", "description": "profiles attribute should contain DASH-IF IOP profile URI", "spec_ref": "DASH-IF IOP v5.0 §4.1", "check": "The MPD `profiles` attribute should include at least one DASH-IF IOP profile URI (containing 'dashif.org') to signal IOP compliance."},
    {"id": "IOP-002", "category": "DASH-IF IOP", "severity": "info", "description": "Recommend SegmentTemplate over SegmentList or SegmentBase", "spec_ref": "DASH-IF IOP v5.0 §4.4.2", "check": "DASH-IF IOP recommends using SegmentTemplate addressing over SegmentList or SegmentBase for better scalability and cacheability."},
    {"id": "IOP-003", "category": "DASH-IF IOP", "severity": "warning", "description": "BaseURL should not be used at Representation level", "spec_ref": "DASH-IF IOP v5.0 §4.3", "check": "IOP recommends placing BaseURL at the AdaptationSet level rather than the Representation level to reduce MPD size and improve cacheability."},
    {"id": "IOP-004", "category": "DASH-IF IOP", "severity": "info", "description": "Video AdaptationSet should have ContentComponent or par attribute", "spec_ref": "DASH-IF IOP v5.0 §4.2", "check": "Video AdaptationSets should declare aspect ratio information via `par` attribute or `ContentComponent` elements for proper rendering."},
]


def get_rules_registry() -> list[dict]:
    return RULES_REGISTRY.copy()
