import { JTAGChain, ChipInfo, SVFOptions, SVFCommandType } from '../types';

export const STANDARD_INSTRUCTIONS: Record<string, string> = {
  BYPASS: '1111',
  EXTEST: '0000',
  SAMPLE: '0001',
  PRELOAD: '0001',
  IDCODE: '0010',
  USERCODE: '0011',
  CLAMP: '0100',
  HIGHZ: '0101',
  INTEST: '0110',
  RUNBIST: '0111'
};

export const TAP_STATES = [
  'RESET',
  'IDLE',
  'DRSELECT',
  'DRCAPTURE',
  'DRSHIFT',
  'DREXIT1',
  'DRPAUSE',
  'DREXIT2',
  'DRUPDATE',
  'IRSELECT',
  'IRUPDATE'
];

function padLeft(str: string, length: number, char: string = '0'): string {
  return char.repeat(Math.max(0, length - str.length)) + str;
}

function hexToBin(hex: string): string {
  const cleanHex = hex.replace(/^0x/i, '').replace(/^X/i, '');
  return cleanHex.split('').map(c => {
    const bin = parseInt(c, 16).toString(2);
    return padLeft(bin, 4, '0');
  }).join('');
}

function binToHex(bits: string): string {
  let paddedBits = padLeft(bits, Math.ceil(bits.length / 4) * 4 - bits.length, '0') + bits;
  let hex = '';
  for (let i = 0; i < paddedBits.length; i += 4) {
    hex += parseInt(paddedBits.substr(i, 4), 2).toString(16);
  }
  return hex.toUpperCase();
}

function reverseBits(bits: string): string {
  return bits.split('').reverse().join('');
}

function bitsToHexData(bits: string): string {
  const paddedBits = padLeft(bits, Math.ceil(bits.length / 4) * 4 - bits.length, '0') + bits;
  let hex = '';
  for (let i = 0; i < paddedBits.length; i += 4) {
    hex += parseInt(paddedBits.substr(i, 4), 2).toString(16);
  }
  return hex.toUpperCase();
}

function formatSVFData(bits: string): string {
  return `(${bitsToHexData(bits)})`;
}

function generateHeaderBits(chain: JTAGChain, targetDevice: number, isIR: boolean): string {
  let headerBits = '';
  for (let i = 0; i < targetDevice; i++) {
    const device = chain.devices[i];
    if (isIR) {
      headerBits += STANDARD_INSTRUCTIONS.BYPASS.repeat(Math.ceil(device.irLength / 4)).slice(0, device.irLength);
    } else {
      headerBits += '0';
    }
  }
  return headerBits;
}

function generateTrailerBits(chain: JTAGChain, targetDevice: number, isIR: boolean): string {
  let trailerBits = '';
  for (let i = targetDevice + 1; i < chain.devices.length; i++) {
    const device = chain.devices[i];
    if (isIR) {
      trailerBits += STANDARD_INSTRUCTIONS.BYPASS.repeat(Math.ceil(device.irLength / 4)).slice(0, device.irLength);
    } else {
      trailerBits += '0';
    }
  }
  return trailerBits;
}

export function generateSVF(chain: JTAGChain, options: SVFOptions): string {
  const lines: string[] = [];
  const { targetDevice, instruction, data, expectedData, mask, endIRState, endDRState, runTestClocks, runTestTime } = options;

  lines.push('! SVF File Generated by JTAG Chain Visualizer');
  lines.push(`! Date: ${new Date().toISOString()}`);
  lines.push(`! Target Device: ${chain.devices[targetDevice]?.name || 'Unknown'}`);
  lines.push('');

  lines.push('ENDIR IDLE;');
  lines.push('ENDDR IDLE;');
  lines.push('');

  const totalIRLength = chain.devices.reduce((sum, d) => sum + d.irLength, 0);
  const device = chain.devices[targetDevice];

  if (!device) {
    throw new Error('Target device not found');
  }

  const headerBitsIR = generateHeaderBits(chain, targetDevice, true);
  const trailerBitsIR = generateTrailerBits(chain, targetDevice, true);

  if (headerBitsIR.length > 0) {
    lines.push(`HIR ${headerBitsIR.length} TDI ${formatSVFData(headerBitsIR)};`);
  }
  if (trailerBitsIR.length > 0) {
    lines.push(`TIR ${trailerBitsIR.length} TDI ${formatSVFData(trailerBitsIR)};`);
  }
  lines.push('');

  let instructionBits = instruction;
  if (STANDARD_INSTRUCTIONS[instruction.toUpperCase()]) {
    instructionBits = STANDARD_INSTRUCTIONS[instruction.toUpperCase()];
    instructionBits = padLeft(instructionBits, device.irLength, '0');
  } else if (/^[0-9A-F]+$/i.test(instruction) && instruction.length <= 8) {
    instructionBits = hexToBin(instruction);
    instructionBits = padLeft(instructionBits, device.irLength, '0');
  }

  lines.push(`SIR ${totalIRLength} TDI ${formatSVFData(instructionBits)};`);
  lines.push('');

  if (headerBitsIR.length > 0) {
    lines.push('HIR 0;');
  }
  if (trailerBitsIR.length > 0) {
    lines.push('TIR 0;');
  }
  lines.push('');

  if (data || expectedData || mask) {
    const headerBitsDR = generateHeaderBits(chain, targetDevice, false);
    const trailerBitsDR = generateTrailerBits(chain, targetDevice, false);

    if (headerBitsDR.length > 0) {
      lines.push(`HDR ${headerBitsDR.length} TDI ${formatSVFData(headerBitsDR)};`);
    }
    if (trailerBitsDR.length > 0) {
      lines.push(`TDR ${trailerBitsDR.length} TDI ${formatSVFData(trailerBitsDR)};`);
    }
    lines.push('');

    const totalDRLength = chain.devices.length + (data?.length || 0) - 1;
    let drParams = '';
    
    if (data) {
      let dataBits = /^[0-9A-F]+$/i.test(data) ? hexToBin(data) : data;
      const fullData = headerBitsDR + dataBits + trailerBitsDR;
      drParams += `TDI ${formatSVFData(fullData)}`;
    }
    
    if (expectedData) {
      let expectedBits = /^[0-9A-F]+$/i.test(expectedData) ? hexToBin(expectedData) : expectedData;
      const fullExpected = headerBitsDR + expectedBits + trailerBitsDR;
      drParams += ` TDO ${formatSVFData(fullExpected)}`;
    }
    
    if (mask) {
      let maskBits = /^[0-9A-F]+$/i.test(mask) ? hexToBin(mask) : mask;
      const fullMask = headerBitsDR + maskBits + trailerBitsDR;
      drParams += ` MASK ${formatSVFData(fullMask)}`;
    }

    if (drParams) {
      lines.push(`SDR ${totalDRLength} ${drParams};`);
    }
    lines.push('');

    if (headerBitsDR.length > 0) {
      lines.push('HDR 0;');
    }
    if (trailerBitsDR.length > 0) {
      lines.push('TDR 0;');
    }
    lines.push('');
  }

  if (runTestClocks || runTestTime) {
    let runtestLine = 'RUNTEST';
    if (runTestClocks) {
      runtestLine += ` ${runTestClocks} TCK`;
    }
    if (runTestTime) {
      runtestLine += ` ${runTestTime} SEC`;
    }
    runtestLine += ' ENDSTATE IDLE;';
    lines.push(runtestLine);
  }

  lines.push('');
  lines.push('! End of SVF');

  return lines.join('\n');
}

export function generateIDCODETest(chain: JTAGChain, deviceIndex: number): string {
  const device = chain.devices[deviceIndex];
  if (!device) return '';

  const expectedIDCODE = device.idcode ? hexToBin(device.idcode) : undefined;

  return generateSVF(chain, {
    targetDevice: deviceIndex,
    instruction: 'IDCODE',
    data: padLeft('', 32, '0'),
    expectedData: expectedIDCODE,
    mask: expectedIDCODE ? padLeft('', 32, '1') : undefined,
    endIRState: 'IDLE',
    endDRState: 'IDLE',
    runTestClocks: 100
  });
}

export function generateSampleTest(chain: JTAGChain, deviceIndex: number): string {
  const device = chain.devices[deviceIndex];
  if (!device) return '';

  const bsrLength = device.boundaryCells.length || 16;
  const sampleData = device.boundaryCells.map(c => c.safeBit || '0').join('');

  return generateSVF(chain, {
    targetDevice: deviceIndex,
    instruction: 'SAMPLE',
    data: padLeft(sampleData, bsrLength, '0'),
    endIRState: 'IDLE',
    endDRState: 'IDLE',
    runTestClocks: 100
  });
}

export function generateExtestTest(chain: JTAGChain, deviceIndex: number): string {
  const device = chain.devices[deviceIndex];
  if (!device) return '';

  const bsrLength = device.boundaryCells.length || 16;
  const testData = padLeft('', bsrLength, '0');

  return generateSVF(chain, {
    targetDevice: deviceIndex,
    instruction: 'EXTEST',
    data: testData,
    endIRState: 'IDLE',
    endDRState: 'IDLE',
    runTestClocks: 1000
  });
}

export function generateBYPASSChain(chain: JTAGChain): string {
  const lines: string[] = [];

  lines.push('! SVF File - BYPASS Chain Test');
  lines.push(`! Date: ${new Date().toISOString()}`);
  lines.push(`! Devices in chain: ${chain.devices.length}`);
  lines.push('');

  lines.push('ENDIR IDLE;');
  lines.push('ENDDR IDLE;');
  lines.push('STATE RESET;');
  lines.push('STATE IDLE;');
  lines.push('');

  const totalIRLength = chain.devices.reduce((sum, d) => sum + d.irLength, 0);
  const bypassInstruction = chain.devices.map(d => 
    padLeft(STANDARD_INSTRUCTIONS.BYPASS, d.irLength, '1')
  ).join('');

  lines.push(`SIR ${totalIRLength} TDI ${formatSVFData(bypassInstruction)};`);
  lines.push('');

  const bypassData = '0'.repeat(chain.devices.length);
  const expectedData = '1'.repeat(chain.devices.length);
  
  lines.push(`SDR ${chain.devices.length} TDI ${formatSVFData(bypassData)} TDO ${formatSVFData(expectedData)} MASK ${formatSVFData(expectedData)};`);
  lines.push('');
  lines.push('RUNTEST 1000 TCK ENDSTATE IDLE;');
  lines.push('');
  lines.push('! End of BYPASS test');

  return lines.join('\n');
}

export function generateFullChainTest(chain: JTAGChain): string {
  const lines: string[] = [];

  lines.push('! SVF File - Full JTAG Chain Test');
  lines.push(`! Date: ${new Date().toISOString()}`);
  lines.push(`! Devices: ${chain.devices.map(d => d.name).join(', ')}`);
  lines.push('');

  lines.push('ENDIR IDLE;');
  lines.push('ENDDR IDLE;');
  lines.push('STATE RESET;');
  lines.push('STATE IDLE;');
  lines.push('');

  chain.devices.forEach((device, index) => {
    lines.push(`! Testing Device ${index + 1}: ${device.name}`);
    lines.push('! ------------------------------');
    
    lines.push(generateIDCODETest(chain, index));
    lines.push('');
  });

  lines.push('! BYPASS Chain Integrity Test');
  lines.push('! ---------------------------');
  lines.push(generateBYPASSChain(chain));

  return lines.join('\n');
}

export function downloadSVF(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.svf') ? filename : `${filename}.svf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function createJTAGChain(devices: ChipInfo[]): JTAGChain {
  const totalIRLength = devices.reduce((sum, d) => sum + d.irLength, 0);
  const totalDRLength = devices.length;

  return {
    devices: [...devices],
    totalIRLength,
    totalDRLength
  };
}
