const fs = require('fs');
const path = require('path');
const os = require('os');

class ReportGenerator {
  constructor(db) {
    this.db = db;
    this.reportTemplate = this.loadTemplate();
  }

  loadTemplate() {
    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GNSS 欺骗检测报告</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #333; padding: 40px; }
    .report-container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow: hidden; }
    .header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 30px 40px; }
    .header h1 { font-size: 28px; margin-bottom: 8px; }
    .header .subtitle { opacity: 0.8; font-size: 14px; }
    .summary-section { padding: 30px 40px; background: #f8f9fa; border-bottom: 1px solid #eee; }
    .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }
    .summary-card { background: white; padding: 20px; border-radius: 10px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
    .summary-card .value { font-size: 36px; font-weight: bold; color: #00d9ff; }
    .summary-card .label { font-size: 12px; color: #666; margin-top: 5px; }
    .summary-card.warning .value { color: #ffa502; }
    .summary-card.danger .value { color: #ff4757; }
    .content-section { padding: 30px 40px; }
    .section-title { font-size: 18px; font-weight: 600; margin-bottom: 20px; padding-bottom: 10px; border-bottom: 2px solid #00d9ff; display: inline-block; }
    .table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    .table th, .table td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #eee; }
    .table th { background: #f8f9fa; font-weight: 600; font-size: 13px; color: #666; }
    .table tr:hover { background: #f8f9fa; }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 12px; font-size: 11px; font-weight: 500; }
    .badge-high { background: #ffebee; color: #c62828; }
    .badge-medium { background: #fff3e0; color: #ef6c00; }
    .badge-low { background: #e3f2fd; color: #1565c0; }
    .satellite-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 15px; margin-top: 15px; }
    .satellite-card { border: 1px solid #eee; border-radius: 10px; padding: 15px; transition: all 0.3s; }
    .satellite-card:hover { border-color: #00d9ff; box-shadow: 0 4px 12px rgba(0,217,255,0.1); }
    .satellite-header { display: flex; align-items: center; margin-bottom: 12px; }
    .satellite-prn { width: 40px; height: 40px; background: linear-gradient(135deg, #00d9ff, #0099cc); border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; margin-right: 12px; }
    .satellite-info { flex: 1; }
    .satellite-info .system { font-size: 11px; color: #999; }
    .satellite-info .snr { font-size: 14px; font-weight: 600; }
    .satellite-stats { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 12px; }
    .satellite-stats .stat { color: #666; }
    .satellite-stats .stat span { color: #333; font-weight: 500; }
    .auth-score { height: 6px; background: #eee; border-radius: 3px; overflow: hidden; margin-top: 8px; }
    .auth-score-fill { height: 100%; transition: width 0.3s; }
    .auth-score-fill.good { background: #4caf50; }
    .auth-score-fill.warning { background: #ff9800; }
    .auth-score-fill.poor { background: #f44336; }
    .detection-methods { margin-top: 10px; display: flex; flex-wrap: wrap; gap: 5px; }
    .method-tag { font-size: 10px; padding: 2px 6px; background: #e3f2fd; color: #1565c0; border-radius: 4px; }
    .footer { padding: 20px 40px; background: #f8f9fa; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; }
    .risk-indicator { display: flex; align-items: center; gap: 10px; }
    .risk-circle { width: 12px; height: 12px; border-radius: 50%; }
    .risk-circle.high { background: #ff4757; animation: pulse 1s infinite; }
    .risk-circle.medium { background: #ffa502; }
    .risk-circle.low { background: #2ed573; }
    @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.5; } }
    .chart-placeholder { background: #f8f9fa; border: 2px dashed #ddd; border-radius: 10px; padding: 40px; text-align: center; color: #999; margin: 20px 0; }
    .metadata { display: flex; justify-content: space-between; font-size: 12px; color: #999; margin-top: 10px; }
  </style>
</head>
<body>
  <div class="report-container">
    <div class="header">
      <h1>🛰️ GNSS 欺骗检测报告</h1>
      <div class="subtitle">Generated by GNSS Spoofing Detector | {{generatedAt}}</div>
    </div>
    
    <div class="summary-section">
      <div class="summary-grid">
        <div class="summary-card">
          <div class="value">{{satelliteCount}}</div>
          <div class="label">可见卫星</div>
        </div>
        <div class="summary-card {{anomalyClass}}">
          <div class="value">{{anomalyCount}}</div>
          <div class="label">异常事件</div>
        </div>
        <div class="summary-card {{unackClass}}">
          <div class="value">{{unacknowledgedCount}}</div>
          <div class="label">未确认警报</div>
        </div>
        <div class="summary-card">
          <div class="value">{{avgAuthScore}}%</div>
          <div class="label">平均认证得分</div>
        </div>
      </div>
      <div class="metadata">
        <span>检测时段: {{timeRange}}</span>
        <span>风险等级: <span class="risk-indicator"><span class="risk-circle {{riskLevel}}"></span> {{riskLevelText}}</span></span>
      </div>
    </div>
    
    <div class="content-section">
      <h2 class="section-title">卫星状态概览</h2>
      <div class="satellite-grid">
        {{satelliteCards}}
      </div>
    </div>
    
    <div class="content-section">
      <h2 class="section-title">异常事件记录 (Top 20)</h2>
      <table class="table">
        <thead>
          <tr>
            <th>时间</th>
            <th>类型</th>
            <th>PRN</th>
            <th>描述</th>
            <th>严重程度</th>
            <th>检测方法</th>
            <th>状态</th>
          </tr>
        </thead>
        <tbody>
          {{anomalyRows}}
        </tbody>
      </table>
    </div>
    
    <div class="content-section">
      <h2 class="section-title">检测系统配置</h2>
      <table class="table">
        <thead>
          <tr>
            <th>检测模块</th>
            <th>状态</th>
            <th>参数配置</th>
          </tr>
        </thead>
        <tbody>
          {{configRows}}
        </tbody>
      </table>
    </div>
    
    <div class="footer">
      <p>本报告由 GNSS Spoofing Detector 自动生成 | 报告生成时间: {{generatedAt}}</p>
      <p style="margin-top: 5px;">⚠️ 此报告仅供参考，专业安全评估请联系技术团队</p>
    </div>
  </div>
</body>
</html>`;
  }

  async generateHTMLReport(options = {}) {
    const satellites = this.db.getSatellites();
    const anomalies = this.db.getAnomalies({
      startTime: options.startTime,
      endTime: options.endTime
    });

    const unacknowledged = anomalies.filter(a => !a.acknowledged);
    const avgAuthScore = satellites.length > 0 
      ? (satellites.reduce((sum, s) => sum + (s.auth_score || 80), 0) / satellites.length).toFixed(1)
      : 0;

    const riskLevel = unacknowledged.length > 5 ? 'high' : unacknowledged.length > 0 ? 'medium' : 'low';
    const riskLevelText = unacknowledged.length > 5 ? '高风险' : unacknowledged.length > 0 ? '中等风险' : '低风险';
    const anomalyClass = anomalies.length > 5 ? 'danger' : anomalies.length > 0 ? 'warning' : '';
    const unackClass = unacknowledged.length > 3 ? 'danger' : unacknowledged.length > 0 ? 'warning' : '';

    const satelliteCards = satellites.slice(0, 16).map(sat => {
      const authScore = sat.auth_score || 80;
      const authClass = authScore >= 80 ? 'good' : authScore >= 60 ? 'warning' : 'poor';
      const snrClass = sat.snr >= 40 ? 'color: #2ed573' : sat.snr >= 30 ? 'color: #ffa502' : 'color: #ff4757';
      
      return `
        <div class="satellite-card">
          <div class="satellite-header">
            <div class="satellite-prn">${sat.prn}</div>
            <div class="satellite-info">
              <div class="system">${sat.system}</div>
              <div class="snr" style="${snrClass}">SNR: ${sat.snr?.toFixed(1) || '--'} dB</div>
            </div>
          </div>
          <div class="satellite-stats">
            <div class="stat">方位: <span>${sat.azimuth?.toFixed(1) || '--'}°</span></div>
            <div class="stat">仰角: <span>${sat.elevation?.toFixed(1) || '--'}°</span></div>
            <div class="stat">伪距: <span>${sat.pseudorange ? (sat.pseudorange/1000).toFixed(1) : '--'}km</span></div>
            <div class="stat">多径: <span>${sat.multipath_confidence > 0.5 ? '是' : '否'}</span></div>
          </div>
          <div class="auth-score">
            <div class="auth-score-fill ${authClass}" style="width: ${authScore}%"></div>
          </div>
          <div class="detection-methods">
            <span class="method-tag">伪距监控</span>
            <span class="method-tag">功率分析</span>
            ${sat.doa_available ? '<span class="method-tag">测向验证</span>' : ''}
            <span class="method-tag">信号认证</span>
          </div>
        </div>
      `;
    }).join('');

    const anomalyRows = anomalies.slice(0, 20).map(a => {
      const severityBadge = `<span class="badge badge-${a.severity}">${a.severity}</span>`;
      const typeLabels = {
        pseudorange_jump: '伪距突变',
        signal_power_spike: '功率突升',
        signal_power_drop: '功率突降',
        low_cn0: '载噪比低',
        unnatural_stability: '异常稳定',
        gradual_pseudorange_drift: '渐进漂移',
        gradual_signal_drift: '信号漂移',
        doa_mismatch: '到达角不符',
        authentication_failure: '认证失败',
        smu_detected: 'SMU检测'
      };
      const methodLabels = {
        abrupt_change: '突变检测',
        CUSUM: 'CUSUM',
        EWMA: 'EWMA',
        stability: '稳定性',
        direction: '测向',
        auth: '认证'
      };
      
      return `
        <tr>
          <td>${new Date(a.timestamp).toLocaleString('zh-CN')}</td>
          <td>${typeLabels[a.type] || a.type}</td>
          <td>${a.satellite_prn || '-'}</td>
          <td style="max-width: 300px;">${a.description}</td>
          <td>${severityBadge}</td>
          <td>${methodLabels[a.detection_method] || a.detection_method || '-'}</td>
          <td>${a.acknowledged ? '✓ 已确认' : '⚠️ 待处理'}</td>
        </tr>
      `;
    }).join('') || '<tr><td colspan="7" style="text-align: center; color: #999;">暂无异常记录</td></tr>';

    const configRows = [
      { name: '伪距突变检测', enabled: true, params: '阈值: 50m' },
      { name: 'CUSUM 渐进漂移检测', enabled: true, params: '阈值: 15, 漂移: 2σ' },
      { name: 'EWMA 信号趋势检测', enabled: true, params: 'α: 0.15, 3σ限' },
      { name: '多径抑制', enabled: true, params: '置信度阈值: 50%' },
      { name: '多天线测向', enabled: true, params: '4天线阵列, 15cm基线' },
      { name: '信号认证验证', enabled: true, params: '奇偶校验/SMU/NMA' },
      { name: '交叉验证', enabled: true, params: 'Z-score > 2.5' }
    ].map(c => `
      <tr>
        <td>${c.name}</td>
        <td>${c.enabled ? '<span style="color: #2ed573;">✓ 启用</span>' : '<span style="color: #999;">✗ 禁用</span>'}</td>
        <td>${c.params}</td>
      </tr>
    `).join('');

    const timeRange = options.startTime 
      ? `${new Date(options.startTime).toLocaleString('zh-CN')} - ${new Date(options.endTime || Date.now()).toLocaleString('zh-CN')}`
      : '全部时段';

    let html = this.reportTemplate
      .replace(/\{\{generatedAt\}\}/g, new Date().toLocaleString('zh-CN'))
      .replace('{{satelliteCount}}', satellites.length)
      .replace('{{anomalyCount}}', anomalies.length)
      .replace('{{unacknowledgedCount}}', unacknowledged.length)
      .replace('{{avgAuthScore}}', avgAuthScore)
      .replace('{{anomalyClass}}', anomalyClass)
      .replace('{{unackClass}}', unackClass)
      .replace('{{riskLevel}}', riskLevel)
      .replace('{{riskLevelText}}', riskLevelText)
      .replace('{{timeRange}}', timeRange)
      .replace('{{satelliteCards}}', satelliteCards)
      .replace('{{anomalyRows}}', anomalyRows)
      .replace('{{configRows}}', configRows);

    const exportPath = path.join(os.homedir(), `GNSS_Report_${Date.now()}.html`);
    fs.writeFileSync(exportPath, html, 'utf8');
    
    return { path: exportPath, html, anomalies, satellites };
  }

  async generateSummaryReport() {
    const satellites = this.db.getSatellites();
    const anomalies = this.db.getAnomalies({});
    
    return {
      generatedAt: new Date().toISOString(),
      summary: {
        totalSatellites: satellites.length,
        totalAnomalies: anomalies.length,
        unacknowledged: anomalies.filter(a => !a.acknowledged).length,
        anomaliesBySeverity: {
          high: anomalies.filter(a => a.severity === 'high').length,
          medium: anomalies.filter(a => a.severity === 'medium').length,
          low: anomalies.filter(a => a.severity === 'low').length
        },
        avgSNR: satellites.length > 0 
          ? satellites.reduce((sum, s) => sum + (s.snr || 0), 0) / satellites.length 
          : 0
      },
      satellites: satellites.map(s => ({
        prn: s.prn,
        system: s.system,
        snr: s.snr,
        elevation: s.elevation,
        status: s.status
      })),
      recentAnomalies: anomalies.slice(0, 10)
    };
  }

  async exportToCSV(options = {}) {
    const anomalies = this.db.getAnomalies(options);
    
    const headers = ['时间', '类型', '卫星PRN', '严重程度', '描述', '检测方法', '确认状态'];
    const rows = anomalies.map(a => [
      new Date(a.timestamp).toLocaleString('zh-CN'),
      a.type,
      a.satellite_prn || '',
      a.severity,
      a.description,
      a.detection_method || '',
      a.acknowledged ? '已确认' : '未确认'
    ]);
    
    const csv = [
      headers.join(','),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
    ].join('\n');
    
    const exportPath = path.join(os.homedir(), `GNSS_Anomalies_${Date.now()}.csv`);
    fs.writeFileSync(exportPath, csv, 'utf8');
    
    return exportPath;
  }
}

module.exports = ReportGenerator;