package config

import (
	"bytes"
	"fmt"
	"strings"

	"ib-subnet-manager/model"
)

type OpenSMExporter struct {
	config model.OpenSMConfig
}

func NewOpenSMExporter(config model.OpenSMConfig) *OpenSMExporter {
	return &OpenSMExporter{config: config}
}

func (e *OpenSMExporter) GenerateConfig() string {
	var buf bytes.Buffer

	buf.WriteString(e.generateHeader())
	buf.WriteString(e.generateGlobalSection())
	buf.WriteString(e.generateRoutingSection())
	buf.WriteString(e.generateAdaptiveRoutingSection())
	buf.WriteString(e.generatePortSection())
	buf.WriteString(e.generateQOSSection())
	buf.WriteString(e.generatePartitionSection())
	buf.WriteString(e.generateEventPluginSection())
	buf.WriteString(e.generateLogSection())
	buf.WriteString(e.generatePerformanceManagerSection())

	return buf.String()
}

func (e *OpenSMExporter) generateHeader() string {
	return `# =============================================================================
# OpenSM Configuration File
# Generated by IB Subnet Manager Simulator
# Format: OpenSM 3.3.x compatible
# =============================================================================

`
}

func (e *OpenSMExporter) generateGlobalSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Global Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	buf.WriteString(fmt.Sprintf("# Subnet Manager GUID\n"))
	if e.config.SmGUID != 0 {
		buf.WriteString(fmt.Sprintf("sm_guid 0x%016x\n", e.config.SmGUID))
	}
	buf.WriteString(fmt.Sprintf("sm_priority %d\n", e.config.Priority))
	buf.WriteString("\n")

	buf.WriteString("# Subnet Parameters\n")
	buf.WriteString(fmt.Sprintf("subnet_prefix 0xfe80000000000000\n"))
	buf.WriteString(fmt.Sprintf("lmc %d\n", e.config.LMC))
	buf.WriteString(fmt.Sprintf("max_op_vl %d\n", e.config.VLCount))
	buf.WriteString(fmt.Sprintf("packet_lifetime 18\n"))
	buf.WriteString(fmt.Sprintf("packet_payload_mtu %d\n", e.config.MTU))
	buf.WriteString("\n")

	buf.WriteString("# SM Behavior\n")
	buf.WriteString("sweep_interval 10\n")
	buf.WriteString("ignore_existing_lft 1\n")
	buf.WriteString("no_partition_enforce 0\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generateRoutingSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Routing Engine Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	buf.WriteString(fmt.Sprintf("routing_engine %s\n", e.config.RoutingEngine))
	buf.WriteString("\n")

	buf.WriteString("# Available routing engines:\n")
	buf.WriteString("#   minhop   - Minimum hop count routing\n")
	buf.WriteString("#   updn     - Up/Down routing (for fat-trees)\n")
	buf.WriteString("#   fattree  - Fat-tree optimized routing\n")
	buf.WriteString("#   torus    - Torus topology routing\n")
	buf.WriteString("#   dfp      - Disjoint Paths routing\n")
	buf.WriteString("#   adaptive - Adaptive routing\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generateAdaptiveRoutingSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Adaptive Routing Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	ar := e.config.AdaptiveRouting

	buf.WriteString(fmt.Sprintf("adaptive_routing %s\n", boolToYesNo(ar.Enabled)))
	if ar.Enabled {
		buf.WriteString(fmt.Sprintf("ar_congestion_threshold %.2f\n", ar.CongestionThreshold))
		buf.WriteString(fmt.Sprintf("ar_min_path_difference %d\n", ar.MinPathDifference))
		buf.WriteString(fmt.Sprintf("ar_rebalance_interval %d\n", ar.RebalanceInterval))
		buf.WriteString(fmt.Sprintf("ar_max_path_changes %d\n", ar.MaxPathChanges))
		buf.WriteString(fmt.Sprintf("ar_use_fcn %s\n", boolToYesNo(ar.UseFCN)))
		buf.WriteString(fmt.Sprintf("ar_use_vl15 %s\n", boolToYesNo(ar.UseVL15)))
	}
	buf.WriteString("\n")

	buf.WriteString("# Adaptive Routing Algorithms:\n")
	buf.WriteString("#   - Congestion-aware routing\n")
	buf.WriteString("#   - Load balancing across multiple paths\n")
	buf.WriteString("#   - FCN (Forwarding Congestion Notification) support\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generatePortSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Port Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	buf.WriteString("# VL Arbitration\n")
	buf.WriteString("vl_high_limit 65535\n")
	buf.WriteString("vl_low_limit 65535\n")
	buf.WriteString("\n")

	buf.WriteString("# SL2VL Mapping\n")
	if len(e.config.SL2VLMap) > 0 {
		buf.WriteString("sl2vl_map")
		for _, vl := range e.config.SL2VLMap {
			buf.WriteString(fmt.Sprintf(" %d", vl))
		}
		buf.WriteString("\n")
	} else {
		buf.WriteString("sl2vl_map 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n")
	}
	buf.WriteString("\n")

	buf.WriteString("# Port Speed/Width Control\n")
	buf.WriteString("max_supported_speed 4\n")
	buf.WriteString("max_supported_width 4\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generateQOSSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# QOS Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	if len(e.config.QOSLevels) > 0 {
		for _, level := range e.config.QOSLevels {
			buf.WriteString(fmt.Sprintf("# QOS Level for SL%d\n", level.SL))
			buf.WriteString(fmt.Sprintf("sl%d_vl %d\n", level.SL, level.VL))
			buf.WriteString(fmt.Sprintf("sl%d_priority %d\n", level.SL, level.Priority))
			buf.WriteString(fmt.Sprintf("sl%d_flow_control %s\n", level.SL, boolToYesNo(level.FlowControl)))
			buf.WriteString("\n")
		}
	} else {
		buf.WriteString("# Default QOS settings\n")
		buf.WriteString("sl0_vl 0\n")
		buf.WriteString("sl1_vl 1\n")
		buf.WriteString("sl1_priority 1\n")
		buf.WriteString("\n")
	}

	return buf.String()
}

func (e *OpenSMExporter) generatePartitionSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Partition Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	buf.WriteString("# P_Key Table\n")
	buf.WriteString("# Format: pkey <pkey_value> <membership>\n")
	buf.WriteString("#   membership: full=1, limited=0\n")
	buf.WriteString("\n")

	if len(e.config.PartitionKeys) > 0 {
		for _, pkey := range e.config.PartitionKeys {
			buf.WriteString(fmt.Sprintf("pkey 0x%04x 1\n", pkey))
		}
	} else {
		buf.WriteString("pkey 0x7fff 1\n")
		buf.WriteString("pkey 0x0001 1\n")
	}
	buf.WriteString("\n")

	buf.WriteString("# IPoIB Partition\n")
	buf.WriteString("ipoib_enforce 0\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generateEventPluginSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Event Plugin Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	if e.config.EventPlugin != "" {
		buf.WriteString(fmt.Sprintf("event_plugin %s\n", e.config.EventPlugin))
		buf.WriteString("event_plugin_opt /var/log/opensm/events.log\n")
	} else {
		buf.WriteString("# event_plugin /usr/lib/opensm/opensm_event_plugin.so\n")
	}
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generateLogSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Logging Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	logLevels := map[string]int{
		"error":   1,
		"warn":    2,
		"info":    3,
		"verbose": 4,
		"debug":   5,
	}

	level := e.config.LogLevel
	if level == "" {
		level = "info"
	}
	buf.WriteString(fmt.Sprintf("log_level %d\n", logLevels[level]))
	buf.WriteString(fmt.Sprintf("log_file /var/log/opensm.log\n"))
	buf.WriteString("max_log_file_size 1048576\n")
	buf.WriteString("log_flush_interval 5\n")
	buf.WriteString("\n")

	return buf.String()
}

func (e *OpenSMExporter) generatePerformanceManagerSection() string {
	var buf bytes.Buffer

	buf.WriteString("# -----------------------------------------------------------------------------\n")
	buf.WriteString("# Performance Manager Configuration\n")
	buf.WriteString("# -----------------------------------------------------------------------------\n\n")

	buf.WriteString(fmt.Sprintf("perfmgr %s\n", boolToYesNo(e.config.PerfMgrEnabled)))
	if e.config.PerfMgrEnabled {
		buf.WriteString("perfmgr_sweep_interval 60\n")
		buf.WriteString("perfmgr_force_scan 1\n")
		buf.WriteString("perfmgr_adaptive_threshold 70\n")
	}
	buf.WriteString("\n")

	buf.WriteString("# Congestion Control\n")
	buf.WriteString("congestion_control 1\n")
	buf.WriteString("cc_sweep_interval 100\n")
	buf.WriteString("cc_threshold 75\n")
	buf.WriteString("cc_sl 1\n")
	buf.WriteString("\n")

	buf.WriteString("# Fabric Monitor\n")
	buf.WriteString(fmt.Sprintf("sa_db_dump %s\n", boolToYesNo(e.config.SAEnabled)))
	buf.WriteString("sa_db_dump_file /var/log/opensm/sa_db.xml\n")
	buf.WriteString("\n")

	return buf.String()
}

func boolToYesNo(b bool) string {
	if b {
		return "1"
	}
	return "0"
}

func GenerateTopologyDot(topology *model.Topology) string {
	var buf bytes.Buffer

	buf.WriteString("graph infiniband_fabric {\n")
	buf.WriteString("    layout=neato;\n")
	buf.WriteString("    overlap=false;\n")
	buf.WriteString("    splines=true;\n")
	buf.WriteString("    node [shape=box, style=filled];\n\n")

	for guid, node := range topology.Nodes {
		var color string
		switch node.NodeType {
		case model.NodeTypeSwitch:
			color = "#4ade80"
		case model.NodeTypeHCA:
			color = "#60a5fa"
		case model.NodeTypeRouter:
			color = "#f59e0b"
		default:
			color = "#888888"
		}

		label := fmt.Sprintf("%s\\n0x%016x", node.Name, guid)
		buf.WriteString(fmt.Sprintf("    \"n%016x\" [label=\"%s\", fillcolor=\"%s\"];\n",
			guid, label, color))
	}

	buf.WriteString("\n")

	for _, node := range topology.Nodes {
		for portNum, port := range node.Ports {
			if port.NeighborGUID == 0 {
				continue
			}
			if node.GUID < port.NeighborGUID {
				linkName := fmt.Sprintf("n%016x:n%016x", node.GUID, port.NeighborGUID)
				revName := fmt.Sprintf("n%016x:n%016x", port.NeighborGUID, node.GUID)
				link := fmt.Sprintf("    \"n%016x\" -- \"n%016x\" [label=\"%d-%d\", taillabel=\"%d\", headlabel=\"%d\"];\n",
					node.GUID, port.NeighborGUID, portNum, port.NeighborPort, portNum, port.NeighborPort)
				if !strings.Contains(buf.String(), linkName) && !strings.Contains(buf.String(), revName) {
					buf.WriteString(link)
				}
			}
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

func GenerateNodeNameMap(topology *model.Topology) string {
	var buf bytes.Buffer

	buf.WriteString("# Node Name Map for OpenSM\n")
	buf.WriteString("# Format: <GUID> <name>\n\n")

	for guid, node := range topology.Nodes {
		buf.WriteString(fmt.Sprintf("0x%016x \"%s\"\n", guid, node.Name))
	}

	return buf.String()
}
