from typing import List, Dict, Tuple
import math

class GCodeExporter:
    def __init__(self, config: Dict = None):
        self.config = config or {
            'feed_rate': 1000,
            'plunge_rate': 300,
            'spindle_speed': 15000,
            'safe_height': 10,
            'cut_depth': 5,
            'units': 'mm',
            'tool_number': 1
        }
    
    def polygon_to_gcode(self, points: List[Tuple[float, float]], start_z: float = 0) -> List[str]:
        gcode = []
        
        if len(points) < 3:
            return gcode
        
        first_point = points[0]
        
        gcode.append(f"G0 Z{self.config['safe_height']}")
        gcode.append(f"G0 X{first_point[0]:.3f} Y{first_point[1]:.3f}")
        gcode.append(f"G1 Z{start_z - self.config['cut_depth']:.3f} F{self.config['plunge_rate']}")
        
        for point in points[1:]:
            gcode.append(f"G1 X{point[0]:.3f} Y{point[1]:.3f} F{self.config['feed_rate']}")
        
        gcode.append(f"G1 X{first_point[0]:.3f} Y{first_point[1]:.3f} F{self.config['feed_rate']}")
        gcode.append(f"G0 Z{self.config['safe_height']}")
        
        return gcode
    
    def generate_header(self) -> List[str]:
        header = [
            f"; G-code generated by Nesting Optimizer",
            f"; Units: {self.config['units']}",
            f"; Tool: T{self.config['tool_number']}",
            f"; Spindle Speed: {self.config['spindle_speed']} RPM",
            f"; Feed Rate: {self.config['feed_rate']} {self.config['units']}/min",
            "",
            "G21",
            "G90",
            "G17",
            f"S{self.config['spindle_speed']} M3",
            f"G0 Z{self.config['safe_height']}",
            ""
        ]
        return header
    
    def generate_footer(self) -> List[str]:
        footer = [
            "",
            f"G0 Z{self.config['safe_height']}",
            "G0 X0 Y0",
            "M5",
            "M30",
            ""
        ]
        return footer
    
    def export(self, placements: List[Dict], cutting_order: List[int]) -> str:
        gcode_lines = []
        
        gcode_lines.extend(self.generate_header())
        
        sorted_placements = sorted(placements, key=lambda p: p.get('cutting_order', 0))
        
        for idx, placement in enumerate(sorted_placements):
            gcode_lines.append(f"; Part {idx + 1}: {placement.get('part_id', 'unknown')}")
            gcode_lines.append(f"; Cutting Order: {idx + 1}")
            
            points = placement.get('points', [])
            part_gcode = self.polygon_to_gcode(points)
            gcode_lines.extend(part_gcode)
            gcode_lines.append("")
        
        gcode_lines.extend(self.generate_footer())
        
        return "\n".join(gcode_lines)
    
    def export_with_path(self, placements: List[Dict], cutting_order: List[int], 
                         travel_path: List[Tuple[float, float]]) -> str:
        gcode_lines = []
        
        gcode_lines.extend(self.generate_header())
        
        gcode_lines.append("; Travel path visualization")
        for i, (x, y) in enumerate(travel_path):
            gcode_lines.append(f"; Travel point {i}: X{x:.2f} Y{y:.2f}")
        gcode_lines.append("")
        
        sorted_placements = sorted(placements, key=lambda p: p.get('cutting_order', 0))
        
        for idx, placement in enumerate(sorted_placements):
            gcode_lines.append(f"; Part {idx + 1}: {placement.get('part_id', 'unknown')}")
            
            points = placement.get('points', [])
            part_gcode = self.polygon_to_gcode(points)
            gcode_lines.extend(part_gcode)
            gcode_lines.append("")
        
        gcode_lines.extend(self.generate_footer())
        
        return "\n".join(gcode_lines)

def export_gcode(placements: List[Dict], cutting_order: List[int], config: Dict = None) -> str:
    exporter = GCodeExporter(config)
    return exporter.export(placements, cutting_order)
