import type { AvcRecord } from '@/types';

export interface AllowRule {
  sourceType: string;
  targetType: string;
  tclass: string;
  permissions: Set<string>;
  id: string;
}

export interface PolicyModule {
  name: string;
  version: string;
  rules: AllowRule[];
}

function extractType(context: string): string {
  const parts = context.split(':');
  return parts[2] || context;
}

export function generateAllowRules(records: AvcRecord[]): AllowRule[] {
  const ruleMap = new Map<string, AllowRule>();

  for (const record of records) {
    const sourceType = extractType(record.scontext);
    const targetType = extractType(record.tcontext);
    const tclass = record.tclass;
    const key = `${sourceType}:${targetType}:${tclass}`;

    if (!ruleMap.has(key)) {
      ruleMap.set(key, {
        sourceType,
        targetType,
        tclass,
        permissions: new Set(),
        id: key,
      });
    }

    const rule = ruleMap.get(key)!;
    for (const perm of record.permissions) {
      rule.permissions.add(perm);
    }
  }

  return Array.from(ruleMap.values()).sort((a, b) => {
    if (a.sourceType !== b.sourceType) {
      return a.sourceType.localeCompare(b.sourceType);
    }
    if (a.targetType !== b.targetType) {
      return a.targetType.localeCompare(b.targetType);
    }
    return a.tclass.localeCompare(b.tclass);
  });
}

export function formatRuleAsAllow(rule: AllowRule): string {
  const perms = Array.from(rule.permissions).sort().join(' ');
  return `allow ${rule.sourceType} ${rule.targetType}:${rule.tclass} { ${perms} };`;
}

export function generateTEFile(
  rules: AllowRule[],
  moduleName: string = 'local_audit2allow',
  version: string = '1.0'
): string {
  const now = new Date();
  const timestamp = now.toISOString().split('T')[0];

  const teContent = `
policy_module(${moduleName}, ${version})

########################################
#
# Policy generated by SELinux AVC Log Analyzer
# Generated: ${timestamp}
#
########################################

${rules.map((rule) => formatRuleAsAllow(rule)).join('\n')}
`;

  return teContent.trim();
}

export function generateAudit2AllowOutput(rules: AllowRule[]): string {
  return `
#============= Generated by audit2allow =============
# Number of allow rules generated: ${rules.length}

${rules.map((rule) => formatRuleAsAllow(rule)).join('\n')}
`.trim();
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
