#
# IDA Pro Python Script for AVR Firmware Analysis
# Firmware: sample_firmware.bin
# Auto-generated by AVR Analyzer
#

from idaapi import *
from idc import *
from idautils import *

print("Loading AVR firmware analysis data...")


# ============================================
# Segment Setup
# ============================================

def setup_segments():
    """Setup AVR memory segments"""
    # Flash memory (0x0000 - 0x7FFF for Atmega328)
    if get_segm_by_name("FLASH") is None:
        add_segm(0, 0x0000, 0x8000, "FLASH", "CODE")
        segm = get_segm_by_name("FLASH")
        set_segm_addressing(segm.start_ea, 1)  # 32-bit addressing
    
    # SRAM (0x0100 - 0x08FF for Atmega328)
    if get_segm_by_name("SRAM") is None:
        add_segm(0, 0x0100, 0x0900, "SRAM", "DATA")
    
    # I/O Registers (0x0020 - 0x005F)
    if get_segm_by_name("IO") is None:
        add_segm(0, 0x0020, 0x0060, "IO", "DATA")
    
    print("Segments setup complete.")


# ============================================
# Function Definitions
# ============================================

def define_functions():
    """Define functions based on analysis"""

    # Function: sub_0000
    # Size: 52 bytes, 13 instructions
    start_ea = 0x0000
    end_ea = 0x0034

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_0000", SN_NOWARN)
            print(f"Created function sub_0000 at 0x0000")
        else:
            print(f"Failed to create function at 0x0000")
    else:
        set_name(start_ea, "sub_0000", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_0000, Size: 52 bytes", 0)

    # Function: sub_0034
    # Size: 29 bytes, 8 instructions
    start_ea = 0x0034
    end_ea = 0x0051

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_0034", SN_NOWARN)
            print(f"Created function sub_0034 at 0x0034")
        else:
            print(f"Failed to create function at 0x0034")
    else:
        set_name(start_ea, "sub_0034", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_0034, Size: 29 bytes", 0)

    # Function: sub_0051
    # Size: 73 bytes, 24 instructions
    start_ea = 0x0051
    end_ea = 0x009A

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_0051", SN_NOWARN)
            print(f"Created function sub_0051 at 0x0051")
        else:
            print(f"Failed to create function at 0x0051")
    else:
        set_name(start_ea, "sub_0051", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_0051, Size: 73 bytes", 0)

    # Function: sub_009A
    # Size: 12 bytes, 6 instructions
    start_ea = 0x009A
    end_ea = 0x00A6

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_009A", SN_NOWARN)
            print(f"Created function sub_009A at 0x009A")
        else:
            print(f"Failed to create function at 0x009A")
    else:
        set_name(start_ea, "sub_009A", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_009A, Size: 12 bytes", 0)

    # Function: sub_00A6
    # Size: 4 bytes, 2 instructions
    start_ea = 0x00A6
    end_ea = 0x00AA

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_00A6", SN_NOWARN)
            print(f"Created function sub_00A6 at 0x00A6")
        else:
            print(f"Failed to create function at 0x00A6")
    else:
        set_name(start_ea, "sub_00A6", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_00A6, Size: 4 bytes", 0)

    # Function: sub_00AA
    # Size: 16 bytes, 8 instructions
    start_ea = 0x00AA
    end_ea = 0x00BA

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_00AA", SN_NOWARN)
            print(f"Created function sub_00AA at 0x00AA")
        else:
            print(f"Failed to create function at 0x00AA")
    else:
        set_name(start_ea, "sub_00AA", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_00AA, Size: 16 bytes", 0)

    # Function: sub_00BA
    # Size: 380 bytes, 190 instructions
    start_ea = 0x00BA
    end_ea = 0x0236

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_00BA", SN_NOWARN)
            print(f"Created function sub_00BA at 0x00BA")
        else:
            print(f"Failed to create function at 0x00BA")
    else:
        set_name(start_ea, "sub_00BA", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_00BA, Size: 380 bytes", 0)

    # Function: sub_0236
    # Size: 570 bytes, 1 instructions
    start_ea = 0x0236
    end_ea = 0x0470

    if get_func(start_ea) is None:
        if add_func(start_ea, end_ea):
            set_name(start_ea, "sub_0236", SN_NOWARN)
            print(f"Created function sub_0236 at 0x0236")
        else:
            print(f"Failed to create function at 0x0236")
    else:
        set_name(start_ea, "sub_0236", SN_NOWARN)

    set_func_cmt(start_ea, "Function: sub_0236, Size: 570 bytes", 0)

    print("Function definitions complete.")

# ============================================
# String Definitions
# ============================================

def define_strings():
    """Define strings based on analysis"""

    # String at 0x00B2
    set_cmt(0x00B2, "String: !P0@", 0)

    print(f"Defined 1 strings.")

# ============================================
# Risk Annotations
# ============================================

def add_risk_comments():
    """Add risk annotations as comments"""

    # MEDIUM: EEPROM_ACCESS_NO_WAIT
    # Function sub_0051 accesses EEPROM but does not check EEPROM ready flag. This can cause corrupted EEPROM reads/writes.
    ea = 0x0082
    set_cmt(ea, "[MEDIUM] EEPROM_ACCESS_NO_WAIT: Function sub_0051 accesses EEPROM but does not check EEPROM ready flag. This can cause corrupted EEPROM reads/writes.", 1)
    set_color(ea, CIC_ITEM, 16776960)

    print(f"Added 1 risk annotations.")

# ============================================
# Instruction Comments
# ============================================

def add_instruction_comments():
    """Add detailed instruction comments"""

    set_cmt(0x0000, "jmp 0x0034", 0)
    set_cmt(0x0004, "jmp 0x0051", 0)
    set_cmt(0x0008, "jmp 0x0051", 0)
    set_cmt(0x000C, "jmp 0x0051", 0)
    set_cmt(0x0010, "jmp 0x0051", 0)
    set_cmt(0x0014, "jmp 0x0051", 0)
    set_cmt(0x0018, "jmp 0x0051", 0)
    set_cmt(0x001C, "jmp 0x0051", 0)
    set_cmt(0x0020, "jmp 0x0051", 0)
    set_cmt(0x0024, "jmp 0x0051", 0)
    set_cmt(0x0028, "jmp 0x0051", 0)
    set_cmt(0x002C, "jmp 0x0051", 0)
    set_cmt(0x0030, "jmp 0x0051", 0)
    set_cmt(0x0034, "jmp 0x0051", 0)
    set_cmt(0x0038, "jmp 0x0051", 0)
    set_cmt(0x003C, "jmp 0x0051", 0)
    set_cmt(0x0040, "jmp 0x0051", 0)
    set_cmt(0x0044, "jmp 0x0051", 0)
    set_cmt(0x0048, "jmp 0x0051", 0)
    set_cmt(0x004C, "jmp 0x0051", 0)
    set_cmt(0x0050, "jmp 0x0051", 0)
    set_cmt(0x0054, "jmp 0x0051", 0)
    set_cmt(0x0058, "jmp 0x0051", 0)
    set_cmt(0x005C, "jmp 0x0051", 0)
    set_cmt(0x0060, "jmp 0x0051", 0)
    set_cmt(0x0064, "jmp 0x0051", 0)
    set_cmt(0x0068, "jmp 0x0051", 0)
    set_cmt(0x006C, "jmp 0x0051", 0)
    set_cmt(0x0070, "jmp 0x0051", 0)
    set_cmt(0x0074, "jmp 0x0051", 0)
    set_cmt(0x0078, "jmp 0x0051", 0)
    set_cmt(0x007C, "jmp 0x0051", 0)
    set_cmt(0x0080, "eor r16, r65", 0)
    set_cmt(0x0082, "out 0x1F, r1", 0)
    set_cmt(0x0084, "ldi r28, 255", 0)
    set_cmt(0x0086, "ldi r29, 4", 0)
    set_cmt(0x0088, "out 0x1E, r29", 0)
    set_cmt(0x008A, "out 0x0D, r28", 0)
    set_cmt(0x008C, "ldi r17, 1", 0)
    set_cmt(0x008E, "ldi r26, 0", 0)
    set_cmt(0x0090, "ldi r27, 1", 0)
    set_cmt(0x0092, "ldi r30, 82", 0)
    set_cmt(0x0094, "ldi r31, 0", 0)
    set_cmt(0x0096, "rjmp .+4", 0)
    set_cmt(0x0098, "lds r0, 0x164", 0)
    set_cmt(0x009A, ".word 0x920D", 0)
    set_cmt(0x009C, "cpi r26, 100", 0)
    set_cmt(0x009E, "cpc r32, r113", 0)
    set_cmt(0x00A0, ".word 0xF7D9", 0)
    set_cmt(0x00A2, "rjmp .+4", 0)
    set_cmt(0x00A4, "cpi r24, 116", 0)
    set_cmt(0x00A6, "cpc r32, r113", 0)
    set_cmt(0x00A8, ".word 0xF7E1", 0)
    set_cmt(0x00AA, "rjmp .+0", 0)
    set_cmt(0x00AC, "cpi r24, 66", 0)
    set_cmt(0x00AE, "cpc r32, r113", 0)
    set_cmt(0x00B0, ".word 0xF7C9", 0)
    set_cmt(0x00B2, "subi r18, 1", 0)
    set_cmt(0x00B4, "sbci r19, 0", 0)
    set_cmt(0x00B6, "sbci r24, 0", 0)
    set_cmt(0x00B8, "andi r30, 113", 0)
    set_cmt(0x00BA, "rjmp .+0", 0)
    set_cmt(0x00BC, "nop", 0)
    set_cmt(0x00BE, "nop", 0)
    set_cmt(0x00C0, "ldi r24, 1", 0)
    set_cmt(0x00C2, "ldi r24, 4", 0)
    set_cmt(0x00C4, "cpi r24, 69", 0)
    set_cmt(0x00C6, "cpc r32, r89", 0)
    set_cmt(0x00C8, ".word 0xF789", 0)
    set_cmt(0x00CA, ".word 0x921F", 0)
    set_cmt(0x00CC, ".word 0x920F", 0)
    set_cmt(0x00CE, ".word 0x921F", 0)
    set_cmt(0x00D0, ".word 0x920F", 0)
    set_cmt(0x00D2, ".word 0x928F", 0)
    set_cmt(0x00D4, ".word 0x929F", 0)
    set_cmt(0x00D6, ".word 0x92AF", 0)
    set_cmt(0x00D8, ".word 0x92BF", 0)
    set_cmt(0x00DA, ".word 0x92CF", 0)
    set_cmt(0x00DC, ".word 0x92DF", 0)
    set_cmt(0x00DE, ".word 0x92EF", 0)
    set_cmt(0x00E0, ".word 0x92FF", 0)
    set_cmt(0x00E2, "mulsu r16, r16", 0)
    set_cmt(0x00E4, "mulsu r17, r17", 0)
    set_cmt(0x00E6, "mulsu r18, r18", 0)
    set_cmt(0x00E8, "mulsu r19, r19", 0)
    set_cmt(0x00EA, "mulsu r20, r20", 0)
    set_cmt(0x00EC, "mulsu r21, r21", 0)
    set_cmt(0x00EE, "mulsu r22, r22", 0)
    set_cmt(0x00F0, "mulsu r23, r23", 0)
    set_cmt(0x00F2, "mulsu r24, r24", 0)
    set_cmt(0x00F4, "mulsu r25, r25", 0)
    set_cmt(0x00F6, "mulsu r26, r26", 0)
    set_cmt(0x00F8, "mulsu r27, r27", 0)
    set_cmt(0x00FA, "mulsu r28, r28", 0)
    set_cmt(0x00FC, "mulsu r29, r29", 0)
    set_cmt(0x00FE, "mulsu r30, r30", 0)
    set_cmt(0x0100, "mulsu r31, r31", 0)
    set_cmt(0x0102, "ld r18, Z", 0)
    set_cmt(0x0104, ".word 0x00B0", 0)
    set_cmt(0x0106, "ld r19, Z", 0)
    set_cmt(0x0108, ".word 0x00B1", 0)
    set_cmt(0x010A, "add r32, r243", 0)
    set_cmt(0x010C, "adc r32, r240", 0)
    set_cmt(0x010E, ".word 0xF009", 0)
    set_cmt(0x0110, "ld r24, Z", 0)
    set_cmt(0x0112, ".word 0x0060", 0)
    set_cmt(0x0114, "subi r24, 255", 0)
    set_cmt(0x0116, "and r32, r56", 0)
    set_cmt(0x0118, "mulsu r24, r24", 0)
    set_cmt(0x011A, ".word 0x0060", 0)
    set_cmt(0x011C, ".word 0x9210", 0)
    set_cmt(0x011E, ".word 0x0061", 0)
    set_cmt(0x0120, "ld r24, Z", 0)
    set_cmt(0x0122, ".word 0x0060", 0)
    set_cmt(0x0124, "andi r24, 127", 0)
    set_cmt(0x0126, "mulsu r24, r24", 0)
    set_cmt(0x0128, ".word 0x0060", 0)
    set_cmt(0x012A, "ld r24, Z", 0)
    set_cmt(0x012C, ".word 0x0061", 0)
    set_cmt(0x012E, "ori r24, 255", 0)
    set_cmt(0x0130, "mulsu r24, r24", 0)
    set_cmt(0x0132, ".word 0x0061", 0)
    set_cmt(0x0134, "ld r24, Z", 0)
    set_cmt(0x0136, ".word 0x0061", 0)
    set_cmt(0x0138, "ori r24, 4", 0)
    set_cmt(0x013A, "mulsu r24, r24", 0)
    set_cmt(0x013C, ".word 0x0061", 0)
    set_cmt(0x013E, "ld r24, Z", 0)
    set_cmt(0x0140, ".word 0x0060", 0)
    set_cmt(0x0142, "ori r24, 255", 0)
    set_cmt(0x0144, "mulsu r24, r24", 0)
    set_cmt(0x0146, ".word 0x0060", 0)
    set_cmt(0x0148, "eor r16, r65", 0)
    set_cmt(0x014A, "subi r24, 255", 0)
    set_cmt(0x014C, "mulsu r24, r24", 0)
    set_cmt(0x014E, ".word 0x0060", 0)
    set_cmt(0x0150, "ld r24, Z", 0)
    set_cmt(0x0152, ".word 0x0061", 0)
    set_cmt(0x0154, "cpi r24, 65", 0)
    set_cmt(0x0156, ".word 0xF409", 0)
    set_cmt(0x0158, ".word 0xCFEE", 0)
    set_cmt(0x015A, "ld r24, Z", 0)
    set_cmt(0x015C, ".word 0x0060", 0)
    set_cmt(0x015E, "ori r24, 255", 0)
    set_cmt(0x0160, "mulsu r24, r24", 0)
    set_cmt(0x0162, ".word 0x0060", 0)
    set_cmt(0x0164, "ld r24, Z", 0)
    set_cmt(0x0166, ".word 0x0061", 0)
    set_cmt(0x0168, "andi r24, 255", 0)
    set_cmt(0x016A, "mulsu r24, r24", 0)
    set_cmt(0x016C, ".word 0x0061", 0)
    set_cmt(0x016E, "ld r24, Z", 0)
    set_cmt(0x0170, ".word 0x0060", 0)
    set_cmt(0x0172, "ori r24, 128", 0)
    set_cmt(0x0174, "mulsu r24, r24", 0)
    set_cmt(0x0176, ".word 0x0060", 0)
    set_cmt(0x0178, "ld r24, Z", 0)
    set_cmt(0x017A, ".word 0x0061", 0)
    set_cmt(0x017C, "andi r25, 255", 0)
    set_cmt(0x017E, "add r32, r248", 0)
    set_cmt(0x0180, "and r32, r56", 0)
    set_cmt(0x0182, "mulsu r24, r24", 0)
    set_cmt(0x0184, ".word 0x0061", 0)
    set_cmt(0x0186, "ld r24, Z", 0)
    set_cmt(0x0188, ".word 0x0061", 0)
    set_cmt(0x018A, "cpse r32, r17", 0)
    set_cmt(0x018C, ".word 0xF019", 0)
    set_cmt(0x018E, "ld r24, Z", 0)
    set_cmt(0x0190, ".word 0x0060", 0)
    set_cmt(0x0192, "ori r24, 24", 0)
    set_cmt(0x0194, "mulsu r24, r24", 0)
    set_cmt(0x0196, ".word 0x0060", 0)
    set_cmt(0x0198, "ld r24, Z", 0)
    set_cmt(0x019A, ".word 0x0061", 0)
    set_cmt(0x019C, "ori r24, 255", 0)
    set_cmt(0x019E, "mulsu r24, r24", 0)
    set_cmt(0x01A0, ".word 0x0061", 0)
    set_cmt(0x01A2, "ld r24, Z", 0)
    set_cmt(0x01A4, ".word 0x0061", 0)
    set_cmt(0x01A6, "ori r24, 4", 0)
    set_cmt(0x01A8, "mulsu r24, r24", 0)
    set_cmt(0x01AA, ".word 0x0061", 0)
    set_cmt(0x01AC, "ld r24, Z", 0)
    set_cmt(0x01AE, ".word 0x0060", 0)
    set_cmt(0x01B0, "ori r24, 255", 0)
    set_cmt(0x01B2, "mulsu r24, r24", 0)
    set_cmt(0x01B4, ".word 0x0060", 0)
    set_cmt(0x01B6, "ld r24, Z", 0)
    set_cmt(0x01B8, ".word 0x0060", 0)
    set_cmt(0x01BA, "ori r24, 128", 0)
    set_cmt(0x01BC, "mulsu r24, r24", 0)
    set_cmt(0x01BE, ".word 0x0060", 0)
    set_cmt(0x01C0, "ld r24, Z", 0)
    set_cmt(0x01C2, ".word 0x0060", 0)
    set_cmt(0x01C4, "ori r25, 255", 0)
    set_cmt(0x01C6, "add r32, r248", 0)
    set_cmt(0x01C8, "and r32, r56", 0)
    set_cmt(0x01CA, "mulsu r24, r24", 0)
    set_cmt(0x01CC, ".word 0x0060", 0)
    set_cmt(0x01CE, "ld r24, Z", 0)
    set_cmt(0x01D0, ".word 0x0060", 0)
    set_cmt(0x01D2, "cpse r32, r17", 0)
    set_cmt(0x01D4, ".word 0xF019", 0)
    set_cmt(0x01D6, "dec r30", 0)
    set_cmt(0x01D8, "lds r15, 0x3E4", 0)
    set_cmt(0x01DA, "lds r14, 0x3E4", 0)
    set_cmt(0x01DC, "lds r13, 0x3E4", 0)
    set_cmt(0x01DE, "lds r12, 0x3E4", 0)
    set_cmt(0x01E0, "lds r11, 0x3E4", 0)
    set_cmt(0x01E2, "lds r10, 0x3E4", 0)
    set_cmt(0x01E4, "lds r9, 0x3E4", 0)
    set_cmt(0x01E6, "lds r8, 0x3E4", 0)
    set_cmt(0x01E8, "lds r7, 0x3E4", 0)
    set_cmt(0x01EA, "lds r6, 0x3E4", 0)
    set_cmt(0x01EC, "lds r5, 0x3E4", 0)
    set_cmt(0x01EE, "lds r4, 0x3E4", 0)
    set_cmt(0x01F0, "lds r3, 0x3E4", 0)
    set_cmt(0x01F2, "lds r2, 0x3E4", 0)
    set_cmt(0x01F4, "lds r1, 0x3E4", 0)
    set_cmt(0x01F6, "lds r0, 0x3E4", 0)
    set_cmt(0x01F8, "lds r15, 0x3E4", 0)
    set_cmt(0x01FA, "lds r14, 0x3E4", 0)
    set_cmt(0x01FC, "lds r13, 0x3E4", 0)
    set_cmt(0x01FE, "lds r12, 0x3E4", 0)
    set_cmt(0x0200, "lds r11, 0x3E4", 0)
    set_cmt(0x0202, "lds r10, 0x3E4", 0)
    set_cmt(0x0204, "lds r9, 0x3E4", 0)
    set_cmt(0x0206, "lds r8, 0x3E4", 0)
    set_cmt(0x0208, "lds r0, 0x3E4", 0)
    set_cmt(0x020A, "lds r1, 0x3E4", 0)
    set_cmt(0x020C, "elpm r29, Z", 0)
    set_cmt(0x020E, "elpm r28, Z", 0)
    set_cmt(0x0210, "elpm r27, Z", 0)
    set_cmt(0x0212, "elpm r26, Z", 0)
    set_cmt(0x0214, "elpm r25, Z", 0)
    set_cmt(0x0216, "elpm r24, Z", 0)
    set_cmt(0x0218, "dec r16", 0)
    set_cmt(0x021A, "eor r16, r65", 0)
    set_cmt(0x021C, "in r24, 0x05", 0)
    set_cmt(0x021E, "ori r24, 128", 0)
    set_cmt(0x0220, "out 0x05, r24", 0)
    set_cmt(0x0222, "subi r24, 255", 0)
    set_cmt(0x0224, "out 0x0C, r24", 0)
    set_cmt(0x0226, "ldi r20, 8", 0)
    set_cmt(0x0228, "ldi r23, 0", 0)
    set_cmt(0x022A, "ldi r24, 0", 0)
    set_cmt(0x022C, "ldi r25, 0", 0)
    set_cmt(0x022E, "cpi r20, 232", 0)
    set_cmt(0x0230, "sbc r16, r129", 0)
    set_cmt(0x0232, "adc r16, r192", 0)
    set_cmt(0x0234, "adc r32, r209", 0)
    set_cmt(0x0236, "brmi .+0", 0)

    print("Instruction comments added.")

# ============================================
# Main Execution
# ============================================

def main():
    """Main script execution"""
    print("=" * 60)
    print("AVR Firmware Analysis IDA Script")
    print("=" * 60)
    print("")
    
    # Setup segments first
    setup_segments()
    print("")
    
    # Define functions
    define_functions()
    print("")
    
    # Define strings
    define_strings()
    print("")
    
    # Add risk comments
    add_risk_comments()
    print("")
    
    # Mark indirect branches
    mark_indirect_branches()
    print("")
    
    # Add instruction comments
    add_instruction_comments()
    print("")
    
    print("=" * 60)
    print("Script execution complete!")
    print("=" * 60)

if __name__ == "__main__":
    main()
