from typing import List, Dict, Optional
from dataclasses import dataclass
import os

from .disassembler import Instruction, Function
from .string_extractor import ExtractedString
from .risk_analyzer import RiskPattern


@dataclass
class IDAExportOptions:
    include_functions: bool = True
    include_comments: bool = True
    include_strings: bool = True
    include_risks: bool = True
    include_segments: bool = True
    rename_functions: bool = True
    add_function_comments: bool = True


class IDAExporter:
    def __init__(self, firmware_name: str = "firmware"):
        self.firmware_name = firmware_name
        self.options = IDAExportOptions()
    
    def _generate_header(self) -> str:
        return f'''#
# IDA Pro Python Script for AVR Firmware Analysis
# Firmware: {self.firmware_name}
# Auto-generated by AVR Analyzer
#

from idaapi import *
from idc import *
from idautils import *

print("Loading AVR firmware analysis data...")

'''
    
    def _generate_segment_setup(self) -> str:
        return '''
# ============================================
# Segment Setup
# ============================================

def setup_segments():
    """Setup AVR memory segments"""
    # Flash memory (0x0000 - 0x7FFF for Atmega328)
    if get_segm_by_name("FLASH") is None:
        add_segm(0, 0x0000, 0x8000, "FLASH", "CODE")
        segm = get_segm_by_name("FLASH")
        set_segm_addressing(segm.start_ea, 1)  # 32-bit addressing
    
    # SRAM (0x0100 - 0x08FF for Atmega328)
    if get_segm_by_name("SRAM") is None:
        add_segm(0, 0x0100, 0x0900, "SRAM", "DATA")
    
    # I/O Registers (0x0020 - 0x005F)
    if get_segm_by_name("IO") is None:
        add_segm(0, 0x0020, 0x0060, "IO", "DATA")
    
    print("Segments setup complete.")

'''
    
    def _generate_function_defs(self, functions: List[Function]) -> str:
        lines = ["\n# ============================================",
                 "# Function Definitions",
                 "# ============================================\n",
                 "def define_functions():",
                 '    """Define functions based on analysis"""',
                 ""]
        
        for func in functions:
            func_name = func.name or f"sub_{func.start_addr:04X}"
            func_size = func.end_addr - func.start_addr if hasattr(func, 'end_addr') else 0
            lines.append(f"    # Function: {func_name}")
            lines.append(f"    # Size: {func_size} bytes, {len(func.instructions)} instructions")
            lines.append(f"    start_ea = 0x{func.start_addr:04X}")
            lines.append(f"    end_ea = 0x{func.end_addr:04X}")
            lines.append("")
            lines.append(f"    if get_func(start_ea) is None:")
            lines.append(f"        if add_func(start_ea, end_ea):")
            if self.options.rename_functions and func.name:
                lines.append(f"            set_name(start_ea, \"{func_name}\", SN_NOWARN)")
            lines.append(f"            print(f\"Created function {func_name} at 0x{func.start_addr:04X}\")")
            lines.append("        else:")
            lines.append(f"            print(f\"Failed to create function at 0x{func.start_addr:04X}\")")
            lines.append("    else:")
            if self.options.rename_functions and func.name:
                lines.append(f"        set_name(start_ea, \"{func_name}\", SN_NOWARN)")
            lines.append("")
            
            if self.options.add_function_comments:
                comment = f"Function: {func_name}, Size: {func_size} bytes"
                lines.append(f"    set_func_cmt(start_ea, \"{comment}\", 0)")
            lines.append("")
        
        lines.append("    print(\"Function definitions complete.\")")
        lines.append("")
        return "\n".join(lines)
    
    def _generate_string_defs(self, strings: List[ExtractedString]) -> str:
        if not strings:
            return ""
        
        lines = ["\n# ============================================",
                 "# String Definitions",
                 "# ============================================\n",
                 "def define_strings():",
                 '    """Define strings based on analysis"""',
                 ""]
        
        for s in strings[:100]:  # Limit to 100 strings to keep script manageable
            escaped_str = s.value.replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')
            lines.append(f"    # String at 0x{s.address:04X}")
            lines.append(f'    set_cmt(0x{s.address:04X}, "String: {escaped_str}", 0)')
            if len(s.value) > 4:
                lines.append(f"    create_strlit(0x{s.address:04X}, 0x{s.address:04X} + {len(s.value)})")
            lines.append("")
        
        lines.append(f"    print(f\"Defined {min(len(strings), 100)} strings.\")")
        lines.append("")
        return "\n".join(lines)
    
    def _generate_risk_comments(self, risks: List[RiskPattern]) -> str:
        if not risks:
            return ""
        
        lines = ["\n# ============================================",
                 "# Risk Annotations",
                 "# ============================================\n",
                 "def add_risk_comments():",
                 '    """Add risk annotations as comments"""',
                 ""]
        
        risk_colors = {
            'critical': 0xFF0000,  # Red
            'high': 0xFF8800,      # Orange
            'medium': 0xFFFF00,    # Yellow
            'low': 0x00FF00,       # Green
        }
        
        for risk in risks:
            level = risk.level.value if hasattr(risk.level, 'value') else risk.level
            color = risk_colors.get(level.lower(), 0xFFFFFF)
            description = risk.description.replace('"', '\\"')
            name = risk.name.replace('"', '\\"')
            
            if risk.instructions:
                addr = risk.instructions[0].address
                lines.append(f"    # {level.upper()}: {name}")
                lines.append(f"    # {description}")
                lines.append(f"    ea = 0x{addr:04X}")
                lines.append(f'    set_cmt(ea, "[{level.upper()}] {name}: {description}", 1)')
                lines.append(f"    set_color(ea, CIC_ITEM, {color})")
                lines.append("")
        
        lines.append(f"    print(f\"Added {len(risks)} risk annotations.\")")
        lines.append("")
        return "\n".join(lines)
    
    def _generate_instruction_comments(self, instructions: List[Instruction]) -> str:
        if not self.options.include_comments:
            return ""
        
        lines = ["\n# ============================================",
                 "# Instruction Comments",
                 "# ============================================\n",
                 "def add_instruction_comments():",
                 '    """Add detailed instruction comments"""',
                 ""]
        
        for insn in instructions[:500]:  # Limit to 500 instructions
            if insn.op_str:
                comment = f"{insn.mnemonic} {insn.op_str}"
            else:
                comment = insn.mnemonic
            
            lines.append(f'    set_cmt(0x{insn.address:04X}, "{comment}", 0)')
        
        lines.append("")
        lines.append("    print(\"Instruction comments added.\")")
        lines.append("")
        return "\n".join(lines)
    
    def _generate_indirect_jump_notes(self, instructions: List[Instruction]) -> str:
        indirect_instructions = [
            insn for insn in instructions 
            if insn.mnemonic in ['ijmp', 'icall', 'eijmp', 'eicall']
        ]
        
        if not indirect_instructions:
            return ""
        
        lines = ["\n# ============================================",
                 "# Indirect Jump/Call Notes",
                 "# ============================================\n",
                 "def mark_indirect_branches():",
                 '    """Mark indirect jumps/calls for special attention"""',
                 ""]
        
        for insn in indirect_instructions:
            lines.append(f"    ea = 0x{insn.address:04X}")
            lines.append(f'    set_cmt(ea, "INDIRECT {insn.mnemonic.upper()} - Verify target address", 1)')
            lines.append(f"    set_color(ea, CIC_ITEM, 0xFF8800)")  # Orange
            lines.append("")
        
        lines.append(f"    print(f\"Marked {len(indirect_instructions)} indirect branches.\")")
        lines.append("")
        return "\n".join(lines)
    
    def _generate_main_execution(self) -> str:
        return '''
# ============================================
# Main Execution
# ============================================

def main():
    """Main script execution"""
    print("=" * 60)
    print("AVR Firmware Analysis IDA Script")
    print("=" * 60)
    print("")
    
    # Setup segments first
    setup_segments()
    print("")
    
    # Define functions
    define_functions()
    print("")
    
    # Define strings
    define_strings()
    print("")
    
    # Add risk comments
    add_risk_comments()
    print("")
    
    # Mark indirect branches
    mark_indirect_branches()
    print("")
    
    # Add instruction comments
    add_instruction_comments()
    print("")
    
    print("=" * 60)
    print("Script execution complete!")
    print("=" * 60)

if __name__ == "__main__":
    main()
'''
    
    def export_script(self, 
                      output_path: str,
                      functions: Optional[List[Function]] = None,
                      instructions: Optional[List[Instruction]] = None,
                      strings: Optional[List[ExtractedString]] = None,
                      risks: Optional[List[RiskPattern]] = None) -> str:
        
        script_content = self._generate_header()
        
        if self.options.include_segments:
            script_content += self._generate_segment_setup()
        
        if self.options.include_functions and functions:
            script_content += self._generate_function_defs(functions)
        
        if self.options.include_strings and strings:
            script_content += self._generate_string_defs(strings)
        
        if self.options.include_risks and risks:
            script_content += self._generate_risk_comments(risks)
        
        if instructions:
            script_content += self._generate_indirect_jump_notes(instructions)
            if self.options.include_comments:
                script_content += self._generate_instruction_comments(instructions)
        
        script_content += self._generate_main_execution()
        
        with open(output_path, 'w') as f:
            f.write(script_content)
        
        return output_path
    
    def export_idc_script(self,
                          output_path: str,
                          functions: Optional[List[Function]] = None,
                          strings: Optional[List[ExtractedString]] = None,
                          risks: Optional[List[RiskPattern]] = None) -> str:
        
        lines = [
            "//",
            "// IDA Pro IDC Script for AVR Firmware Analysis",
            f"// Firmware: {self.firmware_name}",
            "// Auto-generated by AVR Analyzer",
            "//",
            "",
            "#include <idc.idc>",
            "",
            "static main() {",
            '    Message("Loading AVR firmware analysis data...\\n");',
            "",
        ]
        
        if functions:
            lines.append("    // Function Definitions")
            for func in functions:
                func_name = func.name or f"sub_{func.start_addr:04X}"
                lines.append(f"    MakeFunction(0x{func.start_addr:04X}, 0x{func.end_addr:04X});")
                if func.name:
                    lines.append(f'    Rename(0x{func.start_addr:04X}, "{func_name}");')
            lines.append("")
        
        if strings:
            lines.append("    // String Definitions")
            for s in strings[:50]:
                escaped_str = s.value.replace('"', '\\"').replace('\n', ' ')
                lines.append(f'    MakeStr(0x{s.address:04X}, 0x{s.address:04X} + {len(s.value)});')
                lines.append(f'    SetComment(0x{s.address:04X}, "String: {escaped_str}");')
            lines.append("")
        
        if risks:
            lines.append("    // Risk Annotations")
            for risk in risks:
                level = risk.level.value if hasattr(risk.level, 'value') else risk.level
                description = risk.description.replace('"', '\\"')
                name = risk.name.replace('"', '\\"')
                if risk.instructions:
                    addr = risk.instructions[0].address
                    lines.append(f'    SetCommentEx(0x{addr:04X}, "[{level.upper()}] {name}: {description}", 1);')
            lines.append("")
        
        lines.append('    Message("Script execution complete!\\n");')
        lines.append("}")
        
        with open(output_path, 'w') as f:
            f.write("\n".join(lines))
        
        return output_path
